const weeks=window.RUNFEST_WEEKS;
const classLabel={easy:'Rolig',quality:'Kvalitet',race:'Race',rest:'Hvile',cross:'Cross'};
const START=new Date(2026,7,10,12), RACE=new Date(2026,9,3,12), today=new Date();
const shoeMeta={
'Adidas Adios Pro 4':'Race og de viktigste HM-spesifikke øktene. Generalprøve før løpsdagen.',
'Nike Zoom Fly 6':'Primær arbeidshest på terskel, 6×6, 5×8 og 45/15.',
'Xtep 360X 3.0':'Allround/tempo. Rolig test → strides → kvalitet hvis hæl/akilles er rolig.',
'Nike Vomero 18':'Vanlig easy-sko og rolige turer med strides.',
'Nike Vomero 18 Plus':'Primær langtur-sko.',
'Nike Vomero Premium':'Restitusjon på asfalt og dagen etter kvalitet.',
'VJ Ultra 3':'Rolig grus/lett terreng når underlaget og akillesen tillater det.'};
const flat=[];let gi=0;weeks.forEach(w=>w.days.forEach((d,i)=>{flat.push({week:w.n,idx:i,date:addDays(START,gi++),raw:d,type:d[1],title:d[2],desc:d[3],detail:d[4],shoe:d[5],km:Number(d[6]||0),fuel:d[7]||''})}));
const weeksEl=document.getElementById('weeks'), filter=document.getElementById('weekFilter');
weeks.forEach(w=>{const o=document.createElement('option');o.value=w.n;o.textContent=`Uke ${w.n} · ${w.range}`;filter.appendChild(o)});
function addDays(d,n){const r=new Date(d);r.setDate(r.getDate()+n);return r}
function sameDay(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function slug(s){return s.toLowerCase().replace(/[.]/g,'').replace(/\s+/g,'_').replace(/[^a-z0-9æøå_]/g,'')}
function dayKey(label){return `runfest26_date_${label.toLowerCase().replace(/\s+/g,'_')}`}
function fbKey(label){return `runfest26_fb_${slug(label)}`}
function isDone(label){return localStorage.getItem(dayKey(label))==='1'}
function setDone(label,v){localStorage.setItem(dayKey(label),v?'1':'0')}
function getFeedback(label){try{return JSON.parse(localStorage.getItem(fbKey(label))||'{}')}catch{return {}}}
function setFeedback(label,obj){localStorage.setItem(fbKey(label),JSON.stringify(obj))}
function firstShoe(field){if(!field)return'';return field.split('/')[0].replace(/\(.*?\)/g,'').trim()}
function shouldFeedback(f){return f.type==='quality'||f.type==='race'||/langtur/i.test(f.title)}
function fmtPace(sec){const m=Math.floor(sec/60),s=Math.round(sec%60);return `${m}:${String(s).padStart(2,'0')}/km`}
function fmtTime(sec){const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=Math.round(sec%60);return `${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function currentWeek(){const w=weeks.find(w=>{const arr=flat.filter(f=>f.week===w.n);return today>=addDays(arr[0].date,-.5)&&today<addDays(arr[arr.length-1].date,1)});return w||(today<START?weeks[0]:weeks[weeks.length-1])}
function renderCountdown(){const diff=Math.max(0,Math.ceil((RACE-today)/86400000));document.getElementById('countdown').textContent=diff}
function nextSession(){const exact=flat.find(f=>sameDay(f.date,today)&&!isDone(f.raw[0]));if(exact)return exact;const future=flat.find(f=>f.date>today&&!isDone(f.raw[0]));if(future)return future;return flat.find(f=>!isDone(f.raw[0]))||flat[flat.length-1]}
function renderDashboard(){
 const n=nextSession();document.getElementById('nextDate').textContent=sameDay(n.date,today)?'I dag':n.raw[0];document.getElementById('nextTitle').textContent=n.title;document.getElementById('nextDesc').textContent=n.desc;document.getElementById('nextDetail').textContent=n.detail;document.getElementById('nextShoe').textContent=n.shoe?`👟 ${n.shoe}`:'';document.getElementById('nextFuel').textContent=n.fuel?`⚡ ${n.fuel}`:'';
 const w=currentWeek(),wd=flat.filter(f=>f.week===w.n),kmDone=wd.filter(f=>isDone(f.raw[0])).reduce((a,f)=>a+f.km,0),runsDone=wd.filter(f=>isDone(f.raw[0])&&f.km>0).length,runsPlan=wd.filter(f=>f.km>0).length;document.getElementById('weekProgress').style.width=Math.min(100,kmDone/w.km*100)+'%';document.getElementById('weekProgressText').textContent=`Uke ${w.n} · ${kmDone.toFixed(1).replace('.0','')} / ${w.km} km · ${runsDone}/${runsPlan} løpeøkter`;
 renderCoach();renderGateChips();
}
function renderCoach(){
 const entries=flat.map(f=>({f,fb:getFeedback(f.raw[0])})).filter(x=>Object.keys(x.fb).length&&x.f.date<=addDays(today,1));const recent=entries.slice(-3);let level='neutral',title='Uavklart',text='Registrer RPE og akilles etter kvalitet/langtur, så justerer coach-status seg.';
 if(recent.length){const worse=recent.some(x=>x.fb.achilles==='worse'),hard=recent.some(x=>Number(x.fb.rpe)>=9),yellow=recent.some(x=>Number(x.fb.rpe)>=8);if(worse||hard){level='red';title='RØD · avlast neste steg';text=worse?'Siste registreringer viser verre akillesrespons. Bytt neste rolige løp til lett Zwift og vurder utviklingen neste morgen.':'Minst én økt ble svært hard. Ikke legg på ekstra belastning.'}else if(yellow){level='yellow';title='GUL · behold kontroll';text='En nylig økt var RPE 8. Hold neste kvalitetsøkt kontrollert og ikke øk både fart og volum.'}else{level='';title='GRØNN · planen står';text='Registrert respons ser stabil ut. Fortsett uten å skru opp øktene utover planen.'}}
 const el=document.getElementById('coachStatus');el.className='status '+level;document.getElementById('coachTitle').textContent=title;document.getElementById('coachText').textContent=text;
}
function gateVal(n){return localStorage.getItem(`runfest26_gate${n}`)||''}
function renderGateChips(){[1,2].forEach(n=>{const v=gateVal(n),el=document.getElementById(`gateChip${n}`),map={green:'Grønn · kontrollert',yellow:'Gul · måtte jobbe',red:'Rød · måtte presse'};el.className='gateChip '+v;el.querySelector('span').textContent=map[v]||'Ikke vurdert'})}
function renderChart(){const el=document.getElementById('weekChart');el.innerHTML='';const max=Math.max(...weeks.map(w=>w.km));weeks.forEach(w=>{const bw=document.createElement('div');bw.className='barwrap';bw.innerHTML=`<div class="bar" style="height:${Math.round(22+w.km/max*104)}px"><span>${w.km}</span></div><small>U${w.n}</small>`;el.appendChild(bw)})}
function feedbackHTML(f){const fb=getFeedback(f.raw[0]);const shoeOptions=Object.keys(shoeMeta).map(s=>`<option ${fb.shoe===s?'selected':''}>${s}</option>`).join('');const rpes=['','1','2','3','4','5','6','7','8','9','10'].map(v=>`<option value="${v}" ${String(fb.rpe||'')===v?'selected':''}>${v||'RPE'}</option>`).join('');return `<details class="feedback"><summary>Etter økten · registrer respons</summary><div class="feedbackGrid" data-date="${f.raw[0]}"><input name="pace" value="${fb.pace||''}" placeholder="Faktisk fart, f.eks. 4:06/km"><input name="hr" type="number" min="80" max="210" value="${fb.hr||''}" placeholder="Puls arbeidsdel"><select name="rpe">${rpes}</select><select name="achilles"><option value="" ${!fb.achilles?'selected':''}>Akilles neste morgen</option><option value="better" ${fb.achilles==='better'?'selected':''}>Bedre</option><option value="same" ${fb.achilles==='same'?'selected':''}>Lik</option><option value="worse" ${fb.achilles==='worse'?'selected':''}>Verre</option></select><select name="shoe"><option value="">Faktisk sko</option>${shoeOptions}</select><textarea name="note" placeholder="Kort notat (valgfritt)">${fb.note||''}</textarea><div class="feedbackHint">Lagrer automatisk lokalt. Fire felt er nok: fart · puls · RPE · akilles.</div></div></details>`}
function renderWeeks(){
 const val=filter.value;weeksEl.innerHTML='';weeks.filter(w=>val==='all'||String(w.n)===val).forEach(w=>{const sec=document.createElement('section');sec.className='week';const done=flat.filter(f=>f.week===w.n&&isDone(f.raw[0])).length;sec.innerHTML=`<div class="weekhead"><div><span class="phase">${w.phase}</span><h2>Uke ${w.n} · ${w.range}</h2><div class="muted">${w.focus}</div></div><div><b>${w.km} km</b><div class="muted" style="font-size:11px">${done}/7 dager registrert</div></div></div><div class="days"></div>`;const de=sec.querySelector('.days');flat.filter(f=>f.week===w.n).forEach(f=>{const div=document.createElement('article'),done=isDone(f.raw[0]);div.className='day'+(sameDay(f.date,today)?' today':'')+(done?' done':'');div.innerHTML=`<div class="date">${f.raw[0]}</div><h4>${f.title}</h4><span class="badge ${f.type}">${classLabel[f.type]}</span><div class="desc">${f.desc}</div><div class="detail">${f.detail}</div>${f.km?`<div class="micro" style="margin-top:7px">${f.km} km</div>`:''}${f.shoe?`<div class="shoe">👟 ${f.shoe}</div>`:''}${f.fuel?`<div class="fuel">⚡ ${f.fuel}</div>`:''}<label class="checkline"><input type="checkbox" ${done?'checked':''}> Gjennomført</label>${shouldFeedback(f)?feedbackHTML(f):''}`;div.querySelector('.checkline input').addEventListener('change',e=>{setDone(f.raw[0],e.target.checked);renderAll()});de.appendChild(div)});weeksEl.appendChild(sec)});bindFeedback();
}
function bindFeedback(){document.querySelectorAll('.feedbackGrid').forEach(g=>{g.querySelectorAll('input,select,textarea').forEach(inp=>inp.addEventListener('change',()=>{const obj={};g.querySelectorAll('[name]').forEach(x=>{if(x.value)obj[x.name]=x.value});setFeedback(g.dataset.date,obj);renderDashboard();renderShoes()}))})}
function renderShoes(){const wall=document.getElementById('shoeWall'),tot={};Object.keys(shoeMeta).forEach(s=>tot[s]=0);flat.forEach(f=>{if(!isDone(f.raw[0])||f.km<=0)return;const fb=getFeedback(f.raw[0]),s=fb.shoe||firstShoe(f.shoe);if(tot[s]!==undefined)tot[s]+=f.km});wall.innerHTML=Object.keys(shoeMeta).map(s=>`<div class="shoeCard"><div class="shoeKm">${tot[s].toFixed(1).replace('.0','')} km</div><b>${s}</b><p class="muted">${shoeMeta[s]}</p></div>`).join('')}
function updateRace(total=4980){const avg=total/21.0975;document.getElementById('goalPace').textContent=`${fmtTime(total)} · ${fmtPace(avg)}`;const range=(a,b)=>`${fmtPace(avg+a).replace('/km','')}–${fmtPace(avg+b)}`;document.getElementById('rOpen').textContent=range(2,4);document.getElementById('rMid').textContent=range(-1,1);document.getElementById('rLate').textContent=range(-3,0);[5,10,15,20].forEach(k=>document.getElementById('r'+k).textContent=fmtTime(Math.round(avg*k)))}
function updateGateAdvice(){const g1=gateVal(1),g2=gateVal(2),el=document.getElementById('gateAdvice');if(g2==='green'){el.className='callout';el.innerHTML='<b>Grønt lys:</b> 1:23 er et forsvarlig A-mål. Åpne fortsatt kontrollert rundt 3:58–4:00/km.'}else if(g2==='yellow'){el.className='callout warn';el.innerHTML='<b>Gult lys:</b> legg opp til omtrent 1:24-fart (~3:59/km) fra start. Hvis det føles lett etter 10–12 km kan du gradvis nærme deg 1:23-fart.'}else if(g2==='red'){el.className='callout redline';el.innerHTML='<b>Rødt lys:</b> ikke tving 3:56/km. Start rundt 1:24:30–1:25-fart og løp progressivt hvis dagen er god.'}else if(g1==='red'){el.className='callout warn';el.innerHTML='<b>Gate 1 var rød:</b> hold 1:23 som langsiktig A-mål, men ikke øk treningsfarten. Gate 2 får avgjøre endelig raceplan.'}else{el.className='callout warn';el.innerHTML='Vi holder 1:23 som A-mål, men venter på Gate-data før vi låser racefarten.'}renderGateChips()}
function buildStatusText(){const w=currentWeek(),wd=flat.filter(f=>f.week===w.n),done=wd.filter(f=>isDone(f.raw[0])),quality=wd.filter(f=>f.type==='quality'&&isDone(f.raw[0])).map(f=>{const fb=getFeedback(f.raw[0]);return `${f.raw[0]} ${f.title}: ${fb.pace||'fart ikke registrert'}, HR ${fb.hr||'–'}, RPE ${fb.rpe||'–'}, akilles ${fb.achilles||'–'}`});const lastFb=[...flat].reverse().map(f=>({f,fb:getFeedback(f.raw[0])})).find(x=>x.fb.achilles);return `RunnerBear status · uke ${w.n}\nGarmin terskel: 175 bpm · 4:02/km. A-mål: 1:23 (kvalifiseres).\nGjennomført denne uken: ${done.reduce((a,f)=>a+f.km,0).toFixed(1).replace('.0','')} / ${w.km} km.\n${quality.length?'Kvalitetsøkter:\n- '+quality.join('\n- '):'Ingen kvalitetsfeedback registrert denne uken.'}\nSiste akillesstatus: ${lastFb?lastFb.fb.achilles+' ('+lastFb.f.raw[0]+')':'ikke registrert'}.\nGate 1: ${gateVal(1)||'ikke vurdert'} · Gate 2: ${gateVal(2)||'ikke vurdert'}.`}
async function copyStatus(){const text=buildStatusText();try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}const t=document.getElementById('copyToast');t.style.display='block';setTimeout(()=>t.style.display='none',1800)}
function renderAll(){renderCountdown();renderDashboard();renderWeeks();renderShoes();updateGateAdvice()}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')}));
filter.addEventListener('change',renderWeeks);document.querySelectorAll('.goalBtn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.goalBtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');updateRace(Number(b.dataset.goal))}));
[1,2].forEach(n=>{const el=document.getElementById('gate'+n);el.value=gateVal(n);el.addEventListener('change',()=>{localStorage.setItem(`runfest26_gate${n}`,el.value);updateGateAdvice();renderDashboard()})});
document.getElementById('copyStatus').addEventListener('click',copyStatus);document.getElementById('resetChecks').addEventListener('click',()=>{if(confirm('Nullstille avhukinger, feedback og Gate-status?')){Object.keys(localStorage).filter(k=>k.startsWith('runfest26_')).forEach(k=>localStorage.removeItem(k));renderAll()}});
renderChart();updateRace(4980);renderAll();