window.RUNFEST_WEEKS=[
{n:1,range:'10.–16. aug',phase:'Bygge · kontroll',km:52,focus:'Kontrollert terskel + korte 45/15. Ingen hero-økter.',days:[
['Man 10. aug','cross','Zwift lett + styrke','45 min rolig Z1/Z2 + 20 min løpestyrke.','Sykkel 90–100 rpm, lett motstand. Åpne styrkedetaljer i Prinsipper.','',0,''],
['Tir 11. aug','quality','6 × 6 min subterskel','60 s rolig jogg. Totalt ca. 13 km.','Start ca. 4:10–4:12/km og jobb kontrollert mot 4:03–4:05. Puls hovedsakelig 160–170, tak ca. 172. Ikke jag terskelpuls.','Nike Zoom Fly 6',13,'Vanlig måltid 2–3 t før. Ved morgenøkt: 20–30 g karbohydrat før er nok.'],
['Ons 12. aug','easy','7 km rolig','Restitusjon.','HR ca. 130–142. Kort legg/soleus vedlikehold etterpå.','Nike Vomero Premium',7,''],
['Tor 13. aug','easy','7 km + 6 strides','Rolig + 6 × 15 s lett raske.','Avslappet og kontrollert. Full pause mellom strides.','Nike Vomero 18',7,''],
['Fre 14. aug','quality','20 × 45/15','Kontinuerlig 45/15. Totalt ca. 9 km.','Ca. 3:55–4:00/km tidlig, evt. 3:50–3:55 sent. Puls kan nærme seg 170–172. Ingen sluttspurt.','Nike Zoom Fly 6',9,''],
['Lør 15. aug','cross','Concept2 lett / hvile','30–40 min meget rolig eller full hvile.','Velg hvile ved akillesreaksjon eller tunge legger.','',0,''],
['Søn 16. aug','easy','16 km rolig langtur','Rolig og jevnt.','HR ca. 135–145. Ingen progressiv avslutning.','Nike Vomero 18 Plus',16,'Vann etter behov. Ingen gel nødvendig, men øv gjerne på å drikke mens du løper.']]},
{n:2,range:'17.–23. aug',phase:'Bygge · volum',km:55,focus:'Mer terskeltid, fortsatt kontroll.',days:[
['Man 17. aug','cross','Zwift lett + styrke','50–60 min rolig + 20 min styrke.','Ingen hard sykling. Hold beina friske til tirsdag.','',0,''],
['Tir 18. aug','quality','5 × 8 min subterskel','75 s jogg. Totalt ca. 13 km.','Ca. 4:06–4:12/km. Siste drag kan nærme seg 4:03 hvis puls og følelse er gode.','Nike Zoom Fly 6',13,''],
['Ons 19. aug','easy','7 km rolig','Restitusjon.','HR ca. 130–142. Hvis Xtep har kommet: fin første testtur rolig.','Xtep 360X 3.0 / Nike Vomero Premium',7,''],
['Tor 20. aug','easy','8 km + strides','6 × 15 s strides.','Rolig hoveddel, kvikke men avslappede steg.','Nike Vomero 18',8,''],
['Fre 21. aug','quality','3 × 10 × 45/15','2 min rolig mellom seriene. Totalt ca. 10 km.','Serie 1 ~3:58, serie 2 ~3:53, serie 3 ~3:48–3:52 hvis kontroll.','Nike Zoom Fly 6',10,''],
['Lør 22. aug','rest','Hvile','Ingen planlagt trening.','Gåtur er fint.','',0,''],
['Søn 23. aug','easy','17 km rolig langtur','Rolig hele veien.','HR ca. 135–148.','Nike Vomero 18 Plus',17,'Fuel-test #1: 1 gel rundt 45–50 min + litt vann. Noter magefølelse.']]},
{n:3,range:'24.–30. aug',phase:'Bygge · toppstimulus',km:58,focus:'Største terskelvolum så langt + kort X-element.',days:[
['Man 24. aug','cross','Zwift lett + styrke','45–50 min lett + mobilitet/styrke.','Ingen hard sykling.','',0,''],
['Tir 25. aug','quality','4 × 10 min subterskel','90 s jogg. Totalt ca. 14 km.','Ca. 4:05–4:10/km, HR hovedsakelig 160–170. Må føles bedre på drag 4 enn en hard 10 km-økt. Xtep kun hvis rolig test var helt fin.','Xtep 360X 3.0 / Nike Zoom Fly 6',14,''],
['Ons 26. aug','easy','8 km rolig','Restitusjon.','HR 130–142. VJ på grus/lett sti; Premium på asfalt.','VJ Ultra 3 / Nike Vomero Premium',8,''],
['Tor 27. aug','easy','8 km + strides','6 × 15 s lett raske.','Avslappede steg, ikke sprint.','Nike Vomero 18',8,''],
['Fre 28. aug','quality','6 × 3 min X-element','90 s jogg. Totalt ca. 10 km.','Ca. 3:38–3:45/km. RPE 7/10, aldri maks. Flat mølle/vei.','Adidas Adios Pro 4',10,''],
['Lør 29. aug','rest','Hvile / lett roing','Maks 25 min lett Concept2 hvis frisk.','Helst full hvile ved akillesreaksjon.','',0,''],
['Søn 30. aug','easy','18 km langtur','Rolig, stabilt.','HR 135–148.','Nike Vomero 18 Plus',18,'Fuel-test #2: spis frokost/måltid som du kan bruke før Runfest. 1 gel rundt 40–45 min.']]},
{n:4,range:'31. aug–6. sep',phase:'Absorbere',km:50,focus:'Lavere totalbelastning. Behold rytme og spenst.',days:[
['Man 31. aug','rest','Hvile / Zwift 35–40','Kun veldig lett hvis ønskelig.','Ingen styrke hvis beina er slitne.','',0,''],
['Tir 1. sep','quality','5 × 6 min subterskel','60 s jogg. Totalt ca. 11 km.','Ca. 4:04–4:09/km. Garmin 4:02 er terskelanker, ikke mål på hvert drag.','Nike Zoom Fly 6',11,''],
['Ons 2. sep','easy','7 km rolig','Lett og flatt.','HR 130–142.','Nike Vomero Premium',7,''],
['Tor 3. sep','easy','8 km + strides','6 × 15 s.','Kort og kvikt.','Nike Vomero 18',8,''],
['Fre 4. sep','quality','12 × 400 m kontrollert','30–40 s jogg. Totalt ca. 9 km.','Ca. 88–92 s/400 m. Terskelfølelse, ikke baneøkt på maks.','Xtep 360X 3.0',9,''],
['Lør 5. sep','rest','Hvile','Full hvile.','Prioriter søvn.','',0,''],
['Søn 6. sep','easy','15 km rolig','Kortere langtur.','Ingen progresjon.','Nike Vomero 18 Plus',15,'']]},
{n:5,range:'7.–13. sep',phase:'Spesifikk · I',km:57,focus:'Flytt terskelstyrken mot halvmaratonfart. Første beslutningsport.',days:[
['Man 7. sep','cross','Zwift + styrke','45–50 min lett + 20 min styrke.','Siste tyngre styrkeuke.','',0,''],
['Tir 8. sep','quality','4 × 2 km subterskel','60–75 s jogg. Totalt ca. 12 km.','Ca. 4:02–4:06/km. Puls primært 162–171; ingen jakt på 175.','Nike Zoom Fly 6',12,''],
['Ons 9. sep','easy','7 km rolig','Restitusjon.','HR 125–142. VJ på myk grus, Premium på asfalt.','VJ Ultra 3 / Nike Vomero Premium',7,''],
['Tor 10. sep','easy','7 km + 6 strides','Rolig og kvikk avslutning.','Hold strides korte.','Nike Vomero 18',7,''],
['Fre 11. sep','quality','GATE 1 · 3 × 3 km','2 min lett jogg. Totalt ca. 13 km.','4:00–4:03/km på relativt flat asfalt. Kontrollert pust og stabil puls. Du skal kunne tatt ett drag til.','Adidas Adios Pro 4',13,'Ikke gjør dette til ernæringstest. Spis normalt og møt økten med fulle lagre.'],
['Lør 12. sep','rest','Hvile','Ingen trening.','Vurder akillesrespons neste morgen.','',0,''],
['Søn 13. sep','easy','18 km langtur','Siste 4 km kan gå 4:20–4:30 hvis alt er grønt.','Dropp progresjon ved tretthet eller akillesirritasjon.','Nike Vomero 18 Plus',18,'Fuel-test #3: 1 gel ca. 35–40 min. Øv på vanninntak som på løpsdagen.']]},
{n:6,range:'14.–20. sep',phase:'Spesifikk · toppuke',km:60,focus:'Peak. Gate 2 avgjør om 1:23 er riktig A-mål.',days:[
['Man 14. sep','cross','Zwift lett + kort styrke','40–45 min lett + 15 min vedlikehold.','Ingen tunge beinøvelser.','',0,''],
['Tir 15. sep','quality','5 × 7 min subterskel','60–75 s jogg. Totalt ca. 13 km.','Ca. 4:02–4:07/km. Hold igjen og la pulsen ligge under dokumentert terskel. Fredag er viktigst.','Xtep 360X 3.0 / Nike Zoom Fly 6',13,''],
['Ons 16. sep','easy','8 km rolig','Restitusjon.','HR 125–142.','Nike Vomero Premium',8,''],
['Tor 17. sep','easy','7 km + 5 strides','Kort og lett.','Du skal føle deg bedre etter enn før.','Nike Vomero 18',7,''],
['Fre 18. sep','quality','GATE 2 · 3 × 3 km','2 min jogg. Totalt ca. 14 km.','3:55–3:58/km på relativt flat asfalt. Hvis dette krever pressing tidlig, justeres racefart mot 1:24–1:25.','Adidas Adios Pro 4',14,'Bruk samme sko og mest mulig samme før-økt-rutine som Gate 1.'],
['Lør 19. sep','rest','Hvile','Full hvile.','Sjekk morgenstivhet og generell friskhet.','',0,''],
['Søn 20. sep','easy','18 km rolig langtur','Rolig, ikke spesifikk.','Formen bygges nå ved å absorbere, ikke ved å legge på ekstra fart.','Nike Vomero 18 Plus',18,'Race-fuel generalprøve: test planlagt frokost + gel 10–15 min før + gel ca. 35–40 min hvis magen tåler det.']]},
{n:7,range:'21.–27. sep',phase:'Taper · behold fart',km:46,focus:'Reduser volum tydelig, men behold rytme og små doser kvalitet.',days:[
['Man 21. sep','rest','Hvile / 35 min Zwift','Kun lett hvis du liker aktiv rest.','Ingen tung styrke.','',0,''],
['Tir 22. sep','quality','4 × 6 min subterskel','60 s jogg. Totalt ca. 11 km.','Ca. 4:00–4:05/km. Hold under terskel og stopp før det blir hardt.','Nike Zoom Fly 6 / Xtep 360X 3.0',11,''],
['Ons 23. sep','easy','7 km rolig','Virkelig lett.','HR 125–140.','Nike Vomero Premium',7,''],
['Tor 24. sep','easy','7 km + 5 strides','Kort og kvikt.','15 s strides. Full kontroll.','Nike Vomero 18',7,''],
['Fre 25. sep','quality','2 × 3 km HM-spesifikk','2 min jogg. Totalt ca. 9 km.','A-mål: 3:55–3:58/km dersom Gate 2 var grønn. B-mål: 3:59–4:02/km ellers. Skal gi selvtillit, ikke koste form.','Adidas Adios Pro 4',9,'Bruk samme før-økt-rutine som planlagt på løpsdagen.'],
['Lør 26. sep','rest','Hvile','Full hvile.','Ingen kompensasjon for «for lite trening».','',0,''],
['Søn 27. sep','easy','12 km rolig','Kort, behagelig siste langtur.','Rolig hele veien. Du skal avslutte med friske bein.','Nike Vomero 18 Plus',12,'Ingen ernæringstest nå. Bruk bare det du allerede vet fungerer.']]},
{n:8,range:'28. sep–4. okt',phase:'RACE WEEK',km:43.1,focus:'Friskhet, rytme og selvtillit. Ingenting kan bygges nå – bare bevares.',days:[
['Man 28. sep','easy','5 km rolig','Lett og uanstrengt.','HR 125–140.','Nike Vomero Premium',5,''],
['Tir 29. sep','quality','4 × 4 min subterskel','75 s jogg. Totalt ca. 8 km.','Ca. 4:00–4:04/km. Kort økt; la 4:02 kjennes lett og kontrollert. Avslutt med mye igjen.','Nike Zoom Fly 6',8,''],
['Ons 30. sep','easy','5 km rolig','Kort restitusjon.','Ingen styrke.','Nike Vomero Premium',5,''],
['Tor 1. okt','easy','4 km + 4 strides','Rolig + 4 × 15 s.','Bare vekke beina.','Nike Vomero 18',4,''],
['Fre 2. okt','rest','Hvile / valgfri shakeout','Fri eller 15–20 min ekstremt lett.','Ved minste akillesuro: velg hvile.','Nike Vomero 18',0,'Karbohydratrik, normal mat. Ikke eksperimenter. Drikk etter tørste gjennom dagen.'],
['Lør 3. okt','race','RUNFEST 21K','Konkurransedag · Sandnes.','A: 1:23 dersom Gate 2 og siste spesifikke økt er grønne. B: ca. 1:24–1:25 ellers. Åpne 3:58–4:00/km og la løpet komme til deg.','Adidas Adios Pro 4',21.1,'Raceplan: normal frokost 2–3 t før. Hvis testet og tolerert: 1 gel 10–15 min før + 1 gel ca. 35–40 min. Litt vann ved behov.'],
['Søn 4. okt','rest','Restitusjon','Ingen planlagt trening.','Gåtur, mat og søvn.','',0,'']]}
];
