/* RunnerBear v5.11 · backup / restore */
(function(){
  const PREFIX='runfest26_';
  const FORMAT='runnerbear-backup';
  const SCHEMA=1;
  const APP_VERSION='5.11';
  const LAST_EXPORT=PREFIX+'backup_last_export';
  const LAST_IMPORT=PREFIX+'backup_last_import';
  const MAX_BYTES=2*1024*1024;
  let pendingImport=null;

  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function stamp(d=new Date()){const z=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}_${z(d.getHours())}${z(d.getMinutes())}`}
  function friendly(iso){if(!iso)return'aldri';const d=new Date(iso);if(Number.isNaN(d.getTime()))return'ukjent';try{return new Intl.DateTimeFormat('nb-NO',{dateStyle:'medium',timeStyle:'short'}).format(d)}catch{return d.toLocaleString()}}
  function collect(){const items={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith(PREFIX))items[k]=localStorage.getItem(k)??''}return Object.fromEntries(Object.entries(items).sort(([a],[b])=>a.localeCompare(b)))}
  function summary(items){const keys=Object.keys(items||{}),count=re=>keys.filter(k=>re.test(k)).length;let th=0,vo2=0,aero=0,control=0;try{th=JSON.parse(items[PREFIX+'threshold_history']||'[]').length}catch{}try{vo2=JSON.parse(items[PREFIX+'vo2_history']||'[]').length}catch{}try{aero=JSON.parse(items[PREFIX+'aerobic_efficiency_history']||'[]').length}catch{}try{control=JSON.parse(items[PREFIX+'control_history']||'[]').length}catch{}return{completed:count(/^runfest26_date_/),feedback:count(/^runfest26_fb_/),th,vo2,aero,control}}
  function validate(obj,size=0){
    if(size>MAX_BYTES)throw new Error('Filen er større enn 2 MB.');
    if(!obj||typeof obj!=='object'||Array.isArray(obj)||obj.format!==FORMAT||Number(obj.schema)!==SCHEMA)throw new Error('Dette er ikke en støttet RunnerBear-backup.');
    if(!obj.items||typeof obj.items!=='object'||Array.isArray(obj.items))throw new Error('Backupfilen mangler RunnerBear-data.');
    const entries=Object.entries(obj.items);if(entries.length>600)throw new Error('Backupfilen har urimelig mange dataposter.');
    let chars=0;for(const [k,v] of entries){if(!k.startsWith(PREFIX)||typeof v!=='string')throw new Error('Backupfilen inneholder ugyldige data.');chars+=k.length+v.length;if(chars>1200000)throw new Error('Backupfilen inneholder mer data enn forventet.')}
    if(obj.itemCount!=null&&Number(obj.itemCount)!==entries.length)throw new Error('Backupfilen ser ufullstendig ut.');
    return{entries,s:summary(obj.items)};
  }
  async function exportBackup(){
    const now=new Date().toISOString();localStorage.setItem(LAST_EXPORT,now);const items=collect();const obj={format:FORMAT,schema:SCHEMA,appVersion:APP_VERSION,exportedAt:now,event:'Runfest 21K · Sandnes · 2026-10-03',itemCount:Object.keys(items).length,items};
    const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),name=`RunnerBear-backup-${stamp()}.json`;let shared=false;
    try{const file=new File([blob],name,{type:'application/json'});if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'RunnerBear Backup'});shared=true}}catch(e){if(e?.name==='AbortError'){renderStatus();return}}
    if(!shared){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
    const el=$('backupActionStatus');if(el)el.textContent=`Backup laget · ${Object.keys(items).length} dataposter.`;renderStatus();
  }
  async function inspectFile(file){
    pendingImport=null;const p=$('backupPreview');if(!p||!file)return;
    try{if(file.size>MAX_BYTES)throw new Error('Filen er større enn 2 MB.');const text=await file.text();let obj;try{obj=JSON.parse(text)}catch{throw new Error('Filen er ikke gyldig JSON.')}const c=validate(obj,file.size);pendingImport={obj,c,name:file.name};const s=c.s;p.classList.remove('hidden');p.innerHTML=`<div class="backup-preview-head"><b>Backup kontrollert ✓</b><span>${esc(file.name)}</span></div><div class="backup-preview-meta"><span>Eksportert <b>${esc(friendly(obj.exportedAt))}</b></span><span>RunnerBear <b>v${esc(obj.appVersion||'ukjent')}</b></span><span><b>${c.entries.length}</b> dataposter</span></div><div class="backup-preview-counts"><span>✓ ${s.completed} økter</span><span>Respons ${s.feedback}</span><span>Terskel ${s.th}</span><span>VO₂ ${s.vo2}</span><span>Aerob ${s.aero}</span><span>Kontroll ${s.control}</span></div><p>Filen er kontrollert. Gjenoppretting vil erstatte dagens RunnerBear-data etter én ekstra bekreftelse.</p><div class="backup-preview-actions"><button type="button" class="secondary" id="cancelRestore">Avbryt</button><button type="button" class="backup-danger" id="confirmRestore">Gjenopprett denne backupen</button></div>`;$('cancelRestore').onclick=clearPreview;$('confirmRestore').onclick=()=>window.RunnerBearBackup?.restore?.(pendingImport);
    }catch(e){p.classList.remove('hidden');p.innerHTML=`<div class="backup-error"><b>Backupen kan ikke brukes</b><span>${esc(e?.message||'Ukjent feil')}</span></div>`}
  }
  function clearPreview(){pendingImport=null;const p=$('backupPreview');if(p){p.classList.add('hidden');p.innerHTML=''}const f=$('backupFile');if(f)f.value=''}
  function ensureStyle(){if($('runnerBearBackupStyle'))return;const st=document.createElement('style');st.id='runnerBearBackupStyle';st.textContent=`.backup-card{margin-top:16px}.backup-hero{display:grid;grid-template-columns:1fr auto;gap:16px;align-items:center}.backup-hero h2{margin:5px 0 6px}.backup-hero p{margin:0;color:var(--muted);font-size:10.5px;line-height:1.5}.backup-shield{display:grid;place-items:center;width:52px;height:52px;border:1px solid #315341;border-radius:15px;background:#102019;color:var(--green);font-weight:900}.backup-actions{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0 8px}.backup-primary,.backup-file-label,.backup-danger{border:1px solid var(--line);border-radius:10px;padding:10px 12px;font:inherit;font-size:10.5px;cursor:pointer}.backup-primary{background:var(--green);color:#07110b;border-color:var(--green);font-weight:850}.backup-file-label{background:#0d141c;color:var(--text)}.backup-danger{background:#2a1517;color:#f2c3c7;border-color:#6b3038}.backup-badge{font-size:8px;border:1px solid var(--line);padding:3px 6px;border-radius:999px}.backup-badge.green{color:var(--green);border-color:#315341}.backup-badge.yellow{color:var(--yellow);border-color:#5b512e}.backup-status,.backup-foot,.backup-privacy{font-size:9.5px;color:var(--muted)}.backup-status{min-height:14px;margin:7px 0}.backup-foot{display:flex;justify-content:space-between;gap:12px;border-top:1px solid var(--line);padding-top:10px}.backup-foot b,.backup-foot span{display:block}.backup-foot b{color:#cfd7de}.backup-preview{margin:10px 0;padding:11px;border:1px solid var(--line);border-radius:11px;background:#0a1118}.backup-preview-head{display:flex;justify-content:space-between;gap:8px}.backup-preview-head b{color:var(--green)}.backup-preview-head span,.backup-preview-meta{font-size:9px;color:var(--muted)}.backup-preview-meta,.backup-preview-counts{display:flex;gap:9px;flex-wrap:wrap;margin-top:8px}.backup-preview-counts span{font-size:9px;padding:3px 6px;border-radius:999px;background:#ffffff06}.backup-preview p{font-size:9.5px;color:var(--muted);line-height:1.45}.backup-preview-actions{display:flex;gap:7px;flex-wrap:wrap}.backup-error{display:grid;gap:4px;color:#f2c3c7}.backup-privacy{margin:9px 0 0;line-height:1.4}@media(max-width:640px){.backup-hero{grid-template-columns:1fr}.backup-shield{display:none}.backup-actions>*{flex:1;text-align:center}.backup-foot{flex-direction:column}}`;document.head.appendChild(st)}
  function ensureCard(){if($('runnerBearBackupCard'))return;const more=$('more'),danger=more?.querySelector('.danger-zone');if(!danger)return;const card=document.createElement('article');card.id='runnerBearBackupCard';card.className='card backup-card';card.innerHTML=`<div class="kicker"><span>RUNNERBEAR BACKUP</span><span id="backupFreshBadge" class="backup-badge">–</span></div><div class="backup-hero"><div><h2>Ta med historikken videre</h2><p>Eksporter alle RunnerBear-data til én fil. På iPhone brukes delingsarket når det er tilgjengelig.</p></div><div class="backup-shield">RB</div></div><div class="backup-actions"><button type="button" class="backup-primary" id="exportBackup">Eksporter backup</button><label class="backup-file-label" for="backupFile">Gjenopprett fra fil</label><input id="backupFile" type="file" accept="application/json,.json" hidden></div><div id="backupActionStatus" class="backup-status"></div><div id="backupPreview" class="backup-preview hidden"></div><div class="backup-foot"><div><b id="backupFreshText">–</b><span id="backupImportText">–</span></div><button type="button" class="textbtn hidden" id="undoRestore">Angre siste restore</button></div><p class="backup-privacy">Lokalt først: backupinnholdet sendes ikke til en RunnerBear-server.</p>`;danger.insertAdjacentElement('beforebegin',card);$('exportBackup').onclick=exportBackup;$('backupFile').onchange=e=>inspectFile(e.target.files?.[0])}
  function renderStatus(){ensureStyle();ensureCard();const last=localStorage.getItem(LAST_EXPORT),d=last?Math.max(0,Math.floor((Date.now()-new Date(last))/86400000)):null,b=$('backupFreshBadge');if(!b)return;if(d==null){b.className='backup-badge yellow';b.textContent='INGEN BACKUP';$('backupFreshText').textContent='Ta en første backup nå.'}else if(d<=7){b.className='backup-badge green';b.textContent='BACKUP OK';$('backupFreshText').textContent=`Sist eksportert ${friendly(last)}.`}else{b.className='backup-badge yellow';b.textContent=`${d} DAGER`;$('backupFreshText').textContent=`Sist eksportert ${friendly(last)}. Lag gjerne en ny kopi.`}const imp=localStorage.getItem(LAST_IMPORT);$('backupImportText').textContent=imp?`Sist gjenopprettet ${friendly(imp)}.`:'Ingen backup er gjenopprettet på denne enheten.'}

  window.RunnerBearBackup={PREFIX,APP_VERSION,validate,collect,renderStatus,pending:()=>pendingImport};
  ensureStyle();ensureCard();renderStatus();
})();