const weeks=window.RUNFEST_WEEKS;
const classLabel={easy:'Rolig',quality:'Kvalitet',race:'Race',rest:'Hvile',cross:'Cross'};
const START=new Date(2026,7,10,12), RACE=new Date(2026,9,3,12), today=new Date();
const shoeMeta={
'Adidas Adios Pro 4':'Race og de viktigste HM-spesifikke øktene. Generalprøve før løpsdagen.',
'Nike Zoom Fly 6':'Primær arbeidshest på terskel, 6×6, 5×8 og 45/15.',
'Xtep 360X 3.0':'Allround/tempo. Rolig test → strides → kvalitet hvis hæl/akilles er rolig.',
'Nike Vomero 18':'Vanlig easy-sko og rolige turer med strides.',
'Nike Vomero 18 Plus':'Primær langtur-sko.',
'Nike Vomero Premium':'Restitusjon på asfalt og dagen etter kvalitet.',
'VJ Ultra 3':'Rolig grus/lett terreng når underlaget og akillesen tillater det.'};
const flat=[];let gi=0;weeks.forEach(w=>w.days.forEach((d,i)=>flat.push({week:w.n,idx:i,date:addDays(START,gi++),raw:d,type:d[1],title:d[2],desc:d[3],detail:d[4],shoe:d[5],km:Number(d[6]||0),fuel:d[7]||''})));
const weeksEl=document.getElementById('weeks'),filter=document.getElementById('weekFilter'),filterMirror=document.getElementById('weekFilterMirror');
weeks.forEach(w=>{[filter,filterMirror].forEach(sel=>{const o=document.createElement('option');o.value=w.n;o.textContent=`Uke ${w.n} · ${w.range}`;sel.appendChild(o)})});
function addDays(d,n){const r=new Date(d);r.setDate(r.getDate()+n);return r}
function sameDay(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function slug(s){return s.toLowerCase().replace(/[.]/g,'').replace(/\s+/g,'_').replace(/[^a-z0-9æøå_]/g,'')}
function dayKey(label){return `runfest26_date_${label.toLowerCase().replace(/\s+/g,'_')}`}
function fbKey(label){return `runfest26_fb_${slug(label)}`}
function isDone(label){return localStorage.getItem(dayKey(label))==='1'}
function setDone(label,v){localStorage.setItem(dayKey(label),v?'1':'0')}
function getFeedback(label){try{return JSON.parse(localStorage.getItem(fbKey(label))||'{}')}catch{return {}}}
function setFeedback(label,obj){localStorage.setItem(fbKey(label),JSON.stringify(obj))}
function firstShoe(field){if(!field)return'';return field.split('/')[0].replace(/\(.*?\)/g,'').trim()}
function shouldFeedback(f){return f.type==='quality'||f.type==='race'||/langtur/i.test(f.title)}
function fmtPace(sec){const m=Math.floor(sec/60),s=Math.round(sec%60);return `${m}:${String(s).padStart(2,'0')}/km`}
function fmtTime(sec){const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=Math.round(sec%60);return `${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function currentWeek(){const w=weeks.find(w=>{const arr=flat.filter(f=>f.week===w.n);return today>=addDays(arr[0].date,-.5)&&today<addDays(arr[arr.length-1].date,1)});return w||(today<START?weeks[0]:weeks[weeks.length-1])}
function renderCountdown(){document.getElementById('countdown').textContent=Math.max(0,Math.ceil((RACE-today)/86400000))}
function nextSession(){const exact=flat.find(f=>sameDay(f.date,today)&&!isDone(f.raw[0]));if(exact)return exact;const future=flat.find(f=>f.date>today&&!isDone(f.raw[0]));if(future)return future;return flat.find(f=>!isDone(f.raw[0]))||flat[flat.length-1]}
function extractPace(text){const m=String(text).match(/(\d:\d{2})\s*[–-]\s*(\d:\d{2})\s*\/km/i)||String(text).match(/(\d:\d{2})\s*\/km/i);return m?(m[2]?`${m[1]}–${m[2]}`:m[1]):'styr på følelse'}
function extractHr(text){const all=[...String(text).matchAll(/(\d{3})\s*[–-]\s*(\d{3})/g)].map(m=>[Number(m[1]),Number(m[2])]).filter(x=>x[0]>=100&&x[1]<=200);return all.length?`${all[all.length-1][0]}–${all[all.length-1][1]}`:'rolig'}
function extractWork(f){const m=f.title.match(/(\d+\s*[×x]\s*\d+\s*(?:min|m)?)/i);if(m)return m[1].replace(/x/i,'×');if(/langtur/i.test(f.title))return `${f.km} km`;if(f.km)return `${f.km} km`;return classLabel[f.type]}
function renderDashboard(){
 const n=nextSession(),w=currentWeek(),wd=flat.filter(f=>f.week===w.n),kmDone=wd.filter(f=>isDone(f.raw[0])).reduce((a,f)=>a+f.km,0),runsDone=wd.filter(f=>isDone(f.raw[0])&&f.km>0).length,runsPlan=wd.filter(f=>f.km>0).length;
 document.getElementById('phaseNow').textContent=`Uke ${w.n} · ${w.phase}`;document.getElementById('phaseFocus').textContent=w.focus;
 document.getElementById('nextDate').textContent=sameDay(n.date,today)?'I dag':n.raw[0];document.getElementById('nextType').textContent=classLabel[n.type];document.getElementById('nextTitle').textContent=n.title;document.getElementById('nextDesc').textContent=n.desc;document.getElementById('todayPace').textContent=n.type==='quality'||n.type==='race'?extractPace(n.detail):n.type==='easy'?'rolig':'–';document.getElementById('todayHr').textContent=extractHr(n.detail);document.getElementById('todayWork').textContent=extractWork(n);document.getElementById('nextShoe').textContent=n.shoe?`👟 ${n.shoe}`:'';document.getElementById('nextFuel').textContent=n.fuel?`⚡ ${n.fuel}`:'';
 document.getElementById('weekProgress').style.width=Math.min(100,kmDone/w.km*100)+'%';document.getElementById('weekProgressText').textContent=`Uke ${w.n} · ${kmDone.toFixed(1).replace('.0','')} / ${w.km} km · ${runsDone}/${runsPlan} løpeøkter`;document.getElementById('weekKmCompact').textContent=`${kmDone.toFixed(1).replace('.0','')} / ${w.km} km`;document.getElementById('weekRunsCompact').textContent=`${runsDone} / ${runsPlan} løpeøkter`;
 renderCoachStatus();renderGateChips();renderWeekSnapshot(w);syncCoachWhisper();
}
function renderCoachStatus(){
 const entries=flat.map(f=>({f,fb:getFeedback(f.raw[0])})).filter(x=>Object.keys(x.fb).length&&x.f.date<=addDays(today,1)),recent=entries.slice(-3);let level='neutral',title='Uavklart',text='Registrer respons etter kvalitet/langtur.';
 if(recent.length){const worse=recent.some(x=>x.fb.achilles==='worse'),hard=recent.some(x=>Number(x.fb.rpe)>=9),yellow=recent.some(x=>Number(x.fb.rpe)>=8);if(worse||hard){level='red';title='Avlast neste steg';text=worse?'Akillesresponsen var verre. Reduser unødvendig løpsstøt.':'Minst én økt kostet for mye.'}else if(yellow){level='yellow';title='Behold kontroll';text='En nylig økt var RPE 8. Ikke øk både fart og volum.'}else{level='green';title='Planen står';text='Responsen ser stabil ut. Fortsett uten å skru opp planen.'}}
 const sig=document.getElementById('coachStatusSignal');sig.className='statusSignal '+(level==='neutral'?'':level);document.getElementById('coachStatusWord').textContent=level==='green'?'GRØNN':level==='yellow'?'GUL':level==='red'?'RØD':'STATUS';document.getElementById('coachTitle').textContent=title;document.getElementById('coachText').textContent=text;
}
function gateVal(n){return localStorage.getItem(`runfest26_gate${n}`)||''}
function renderGateChips(){const g1=gateVal(1),g2=gateVal(2),txt=g2==='green'?'1:23 kvalifisert':g2==='yellow'?'Nær · ca. 1:24':g2==='red'?'Ikke kvalifisert':g1==='green'?'Gate 1 grønn':g1?'Gate 1 vurdert':'Ikke startet';document.getElementById('gateCompact').textContent=txt}
function renderWeekSnapshot(w){const arr=flat.filter(f=>f.week===w.n);document.getElementById('weekSnapshotTitle').textContent=`Uke ${w.n} · ${w.range}`;document.getElementById('weekSnapshotList').innerHTML=arr.map(f=>`<div class="weekMini ${sameDay(f.date,today)?'today':''} ${isDone(f.raw[0])?'done':''}"><span class="d">${f.raw[0].split(' ')[0]}</span><b>${f.title}</b><span class="tick">${isDone(f.raw[0])?'✓':sameDay(f.date,today)?'I DAG':''}</span></div>`).join('')}
function renderChart(){const el=document.getElementById('weekChart');el.innerHTML='';const max=Math.max(...weeks.map(w=>w.km));weeks.forEach(w=>{const bw=document.createElement('div');bw.className='barwrap';bw.innerHTML=`<div class="bar" style="height:${Math.round(18+w.km/max*88)}px"><span>${w.km}</span></div><small>U${w.n}</small>`;el.appendChild(bw)})}
function feedbackHTML(f){const fb=getFeedback(f.raw[0]),shoeOptions=Object.keys(shoeMeta).map(s=>`<option value="${s}" ${fb.shoe===s?'selected':''}>${s}</option>`).join(''),rpes=['','1','2','3','4','5','6','7','8','9','10'].map(v=>`<option value="${v}" ${String(fb.rpe||'')===v?'selected':''}>${v?`RPE ${v}`:'RPE'}</option>`).join('');return `<details class="feedback"><summary>✓ Etter økten</summary><div class="feedbackGrid" data-date="${f.raw[0]}"><div class="feedbackPrimary"><select name="rpe">${rpes}</select><select name="achilles"><option value="" ${!fb.achilles?'selected':''}>Akilles neste morgen</option><option value="better" ${fb.achilles==='better'?'selected':''}>Bedre</option><option value="same" ${fb.achilles==='same'?'selected':''}>Lik</option><option value="worse" ${fb.achilles==='worse'?'selected':''}>Verre</option></select></div><div class="feedbackExtra"><details><summary>Legg til fart, puls, sko eller notat</summary><div class="extraGrid"><input name="pace" value="${fb.pace||''}" placeholder="Faktisk fart"><input name="hr" type="number" min="80" max="210" value="${fb.hr||''}" placeholder="Puls arbeidsdel"><select name="shoe"><option value="">Faktisk sko</option>${shoeOptions}</select><textarea name="note" placeholder="Kort notat">${fb.note||''}</textarea><div class="feedbackHint">Lagrer automatisk. RPE + akilles er viktigst; resten er bonus.</div></div></details></div></div></details>`}
function renderWeeks(){
 const val=filter.value;weeksEl.innerHTML='';weeks.filter(w=>val==='all'||String(w.n)===val).forEach(w=>{const sec=document.createElement('section');sec.className='week';const done=flat.filter(f=>f.week===w.n&&isDone(f.raw[0])).length;sec.innerHTML=`<div class="weekhead"><div><span class="phase">${w.phase}</span><h2>Uke ${w.n} · ${w.range}</h2><div class="muted" style="font-size:11px">${w.focus}</div></div><div><b>${w.km} km</b><div class="muted" style="font-size:10px">${done}/7 registrert</div></div></div><div class="days"></div>`;const de=sec.querySelector('.days');flat.filter(f=>f.week===w.n).forEach(f=>{const done=isDone(f.raw[0]),details=document.createElement('details');details.className='day'+(sameDay(f.date,today)?' today':'')+(done?' done':'');if(sameDay(f.date,today))details.open=true;details.innerHTML=`<summary class="daySummary"><span class="sdate">${f.raw[0]}</span><b>${f.title}</b><span class="state">${done?'✓':sameDay(f.date,today)?'I DAG':'›'}</span></summary><div class="dayBody"><div class="date">${f.raw[0]}</div><h4>${f.title}</h4><span class="badge">${classLabel[f.type]}</span><div class="desc">${f.desc}</div><div class="detail">${f.detail}</div>${f.km?`<div class="micro" style="margin-top:7px">${f.km} km</div>`:''}${f.shoe?`<div class="shoe">👟 ${f.shoe}</div>`:''}${f.fuel?`<div class="fuel">⚡ ${f.fuel}</div>`:''}<label class="checkline"><input type="checkbox" ${done?'checked':''}> Gjennomført</label>${shouldFeedback(f)?feedbackHTML(f):''}</div>`;details.querySelector('.checkline input').addEventListener('change',e=>{setDone(f.raw[0],e.target.checked);renderAll()});de.appendChild(details)});weeksEl.appendChild(sec)});bindFeedback();
}
function bindFeedback(){document.querySelectorAll('.feedbackGrid').forEach(g=>g.querySelectorAll('input,select,textarea').forEach(inp=>inp.addEventListener('change',()=>{const obj={};g.querySelectorAll('[name]').forEach(x=>{if(x.value)obj[x.name]=x.value});setFeedback(g.dataset.date,obj);renderDashboard();renderShoes()})))}
function renderShoes(){const wall=document.getElementById('shoeWall'),tot={};Object.keys(shoeMeta).forEach(s=>tot[s]=0);flat.forEach(f=>{if(!isDone(f.raw[0])||f.km<=0)return;const fb=getFeedback(f.raw[0]),s=fb.shoe||firstShoe(f.shoe);if(tot[s]!==undefined)tot[s]+=f.km});wall.innerHTML=Object.keys(shoeMeta).map(s=>`<div class="shoeCard"><div class="shoeKm">${tot[s].toFixed(1).replace('.0','')} km</div><b>${s}</b><p class="muted">${shoeMeta[s]}</p></div>`).join('')}
function updateRace(total=4980){const avg=total/21.0975;document.getElementById('goalPace').textContent=`${fmtTime(total)} · ${fmtPace(avg)}`;const range=(a,b)=>`${fmtPace(avg+a).replace('/km','')}–${fmtPace(avg+b)}`;document.getElementById('rOpen').textContent=range(2,4);document.getElementById('rMid').textContent=range(-1,1);document.getElementById('rLate').textContent=range(-3,0);[5,10,15,20].forEach(k=>document.getElementById('r'+k).textContent=fmtTime(Math.round(avg*k)))}
function updateGateAdvice(){const g1=gateVal(1),g2=gateVal(2),el=document.getElementById('gateAdvice');if(g2==='green'){el.className='callout';el.innerHTML='<b>Grønt lys:</b> 1:23 er et forsvarlig A-mål. Åpne fortsatt kontrollert.'}else if(g2==='yellow'){el.className='callout warn';el.innerHTML='<b>Gult lys:</b> start omtrent på 1:24-fart og la løpet utvikle seg.'}else if(g2==='red'){el.className='callout redline';el.innerHTML='<b>Rødt lys:</b> ikke tving 3:56/km. Start rundt 1:24:30–1:25.'}else if(g1==='red'){el.className='callout warn';el.innerHTML='<b>Gate 1 rød:</b> ikke øk treningsfarten. Gate 2 får avgjøre.'}else{el.className='callout warn';el.innerHTML='1:23 er A-målet, men skal kvalifiseres av Gate-data.'}renderGateChips()}
function buildStatusText(){const w=currentWeek(),wd=flat.filter(f=>f.week===w.n),done=wd.filter(f=>isDone(f.raw[0])),quality=wd.filter(f=>f.type==='quality'&&isDone(f.raw[0])).map(f=>{const fb=getFeedback(f.raw[0]);return `${f.raw[0]} ${f.title}: ${fb.pace||'fart –'}, HR ${fb.hr||'–'}, RPE ${fb.rpe||'–'}, akilles ${fb.achilles||'–'}`}),lastFb=[...flat].reverse().map(f=>({f,fb:getFeedback(f.raw[0])})).find(x=>x.fb.achilles);return `RunnerBear status · uke ${w.n}\nGarmin terskel: 175 bpm · 4:02/km. A-mål: 1:23 (kvalifiseres).\nGjennomført: ${done.reduce((a,f)=>a+f.km,0).toFixed(1).replace('.0','')} / ${w.km} km.\n${quality.length?'Kvalitet:\n- '+quality.join('\n- '):'Ingen kvalitetsfeedback denne uken.'}\nSiste akillesstatus: ${lastFb?lastFb.fb.achilles+' ('+lastFb.f.raw[0]+')':'ikke registrert'}.\nGate 1: ${gateVal(1)||'ikke vurdert'} · Gate 2: ${gateVal(2)||'ikke vurdert'}.`}
async function copyStatus(){const text=buildStatusText();try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}const t=document.getElementById('copyToast');t.style.display='inline';setTimeout(()=>t.style.display='none',1800)}
function syncCoachWhisper(){const src=document.querySelector('#coachPlus .coachHero h2'),body=document.querySelector('#coachPlus .coachHero p'),out=document.getElementById('todayCoach');if(out)out.textContent=src&&body?`${src.textContent}. ${body.textContent}`:'Gjennomfør kontrollert.'}
function activateTab(id){document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='plan'&&filter.value==='all'){const w=currentWeek();filter.value=String(w.n);filterMirror.value=String(w.n);renderWeeks()}}
function resetAll(){if(confirm('Nullstille avhukinger, feedback og Gate-status?')){Object.keys(localStorage).filter(k=>k.startsWith('runfest26_')).forEach(k=>localStorage.removeItem(k));renderAll()}}
function renderAll(){renderCountdown();renderDashboard();renderWeeks();renderShoes();updateGateAdvice()}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.tab)));document.querySelectorAll('.navTarget').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.target)));
filter.addEventListener('change',()=>{filterMirror.value=filter.value;renderWeeks()});filterMirror.addEventListener('change',()=>{filter.value=filterMirror.value;renderWeeks()});
document.querySelectorAll('.goalBtn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.goalBtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');updateRace(Number(b.dataset.goal))}));
[1,2].forEach(n=>{const el=document.getElementById('gate'+n);el.value=gateVal(n);el.addEventListener('change',()=>{localStorage.setItem(`runfest26_gate${n}`,el.value);updateGateAdvice();renderDashboard()})});
document.getElementById('copyStatus').addEventListener('click',copyStatus);document.getElementById('resetChecks').addEventListener('click',resetAll);document.getElementById('resetChecksMore').addEventListener('click',resetAll);
renderChart();updateRace(4980);renderAll();
/* RunnerBear Coach · regelbasert, Bakken-inspirert */
(function(){
function pct(n,d){return d?Math.round(n/d*100):0}
function qualityEntriesForWeek(w){return flat.filter(f=>f.week===w.n&&f.type==='quality'&&isDone(f.raw[0]))}
function feedbackEntriesForWeek(w){return flat.filter(f=>f.week===w.n).map(f=>({f,fb:getFeedback(f.raw[0])})).filter(x=>Object.keys(x.fb).length)}
function nextCoachMessage(){const n=nextSession(),recent=[...flat].reverse().map(f=>({f,fb:getFeedback(f.raw[0])})).find(x=>Object.keys(x.fb).length),worse=recent&&recent.fb.achilles==='worse';if(worse)return{tone:'red',title:'Akilles først',text:'Siste respons var verre. Ikke vinn dagens økt. Reduser unødvendig løpsstøt til responsen er tilbake på normalen.'};if(n.type==='quality'){if(/GATE 2/i.test(n.title))return{tone:'gold',title:'Test – ikke eksamen',text:'Gate 2 skal vise om 3:56/km er kontrollert nok. Åpne disiplinert og la testen gi svaret.'};if(/GATE 1/i.test(n.title))return{tone:'gold',title:'Kontroll er svaret',text:'Jevn fart, stabil puls og følelsen av ett drag til er bedre enn en rask avslutning.'};if(/45\/15|400|X-element/i.test(n.title))return{tone:'green',title:'Flyt før fart',text:'Korte drag tåler fart, men økten skal fortsatt være repeterbar. Ingen sluttspurt.'};return{tone:'green',title:'Bygg terskel – ikke ego',text:'Start et hakk roligere enn du føler du kan. Hvis steg og pust er stabile sent, får farten komme til deg.'}}if(n.type==='easy')return{tone:'green',title:'Rolig betyr produktivt',text:'Dagens jobb er å absorbere kvaliteten. Hold steget avslappet og pulsen rolig.'};if(n.type==='cross')return{tone:'green',title:'Aerob bonus uten støt',text:'Kryss-treningen skal støtte løpingen, ikke konkurrere med den.'};if(n.type==='rest')return{tone:'green',title:'Hvile er en del av blokken',text:'Ikke kompenser. Friskhet er en treningsvariabel.'};if(n.type==='race')return{tone:'gold',title:'Nå handler det om utførelse',text:'Første 2–3 km skal føles nesten for enkle. La løpet komme til deg.'};return{tone:'green',title:'Hold kurs',text:'Kontinuitet slår enkeltøkter.'}}
function weekReview(){const w=currentWeek(),wd=flat.filter(f=>f.week===w.n),completed=wd.filter(f=>isDone(f.raw[0])),km=completed.reduce((a,f)=>a+f.km,0),q=qualityEntriesForWeek(w),fbs=feedbackEntriesForWeek(w),rpes=fbs.map(x=>Number(x.fb.rpe)).filter(Boolean),avgRpe=rpes.length?(rpes.reduce((a,b)=>a+b,0)/rpes.length).toFixed(1):null,worse=fbs.some(x=>x.fb.achilles==='worse'),todayIdx=wd.findIndex(f=>sameDay(f.date,today)),due=todayIdx>=0?wd.slice(0,todayIdx+1):(today>wd[wd.length-1].date?wd:[]),adherence=pct(due.filter(f=>isDone(f.raw[0])).length,due.length);let verdict='Uken bygges',tone='neutral',review='Hold deg til planen og registrer respons etter kvalitet/langtur.';if(due.length){if(worse){verdict='Juster belastningen';tone='red';review='Akillesresponsen veier tyngst. Behold aerob rytme, men fjern unødvendig løpsstøt.'}else if(rpes.some(r=>r>=8)){verdict='Kontroll før progresjon';tone='yellow';review='Minst én økt kostet mer enn ønskelig. Målet er samme kvalitet til lavere kostnad.'}else if(adherence>=85){verdict='Godkjent – hold kurs';tone='green';review='Kontinuiteten er god. Ikke belønn en god uke med å gjøre neste uke hardere enn planen.'}else if(adherence<70){verdict='Prioriter nøkkeløktene';tone='yellow';review='Ikke jag tapte kilometer. Finn rytmen igjen gjennom neste nøkkeløkt.'}}const nextKey=flat.find(f=>f.week===Math.min(8,w.n+1)&&f.type==='quality')||nextSession();return{w,km,q,avgRpe,verdict,tone,review,focus:nextKey.title}}
function readiness(){const g1=gateVal(1),g2=gateVal(2),qualityDone=flat.filter(f=>f.type==='quality'&&isDone(f.raw[0])).length,fb=flat.map(f=>({f,fb:getFeedback(f.raw[0])})).filter(x=>x.f.type==='quality'&&Object.keys(x.fb).length),good=fb.filter(x=>Number(x.fb.rpe)>0&&Number(x.fb.rpe)<=6&&x.fb.achilles!=='worse').length;let level=1,label='BYGGES',text='1:23 er et A-mål, men er ikke dokumentert av terskelestimatet alene.';if(qualityDone>=3||good>=2){level=2;label='PÅ VEI';text='Kontinuiteten bygger grunnlaget. Vi trenger spesifikk bekreftelse.'}if(g1==='green'){level=3;label='NÆRMER SEG';text='Gate 1 var kontrollert. Gate 2 er fortsatt nøkkeltesten.'}if(g1==='yellow'){level=Math.max(level,2);label='PÅ VEI';text='Gate 1 var nyttig, men ikke tydelig grønn. Ikke tving utviklingen.'}if(g1==='red'){level=1;label='MÅ BYGGES';text='Gate 1 kostet for mye. Tren etter dagens kapasitet.'}if(g2==='yellow'){level=3;label='NÆR – IKKE LÅST';text='Gate 2 var nesten der. Raceplan bør foreløpig lene mot 1:24.'}if(g2==='red'){level=2;label='IKKE KVALIFISERT';text='Gate 2 var for hard. 3:56/km skal ikke tvinges.'}if(g2==='green'){level=4;label='KVALIFISERT';text='Gate 2 var kontrollert. 1:23 kan brukes som A-mål med kontrollert åpning.'}return{level,label,text,g1,g2}}
function renderCoach(){const host=document.getElementById('coachPlus');if(!host)return;const msg=nextCoachMessage(),r=weekReview(),rd=readiness(),steps=[{label:'Nå',on:true,current:!rd.g1},{label:'Gate 1',on:!!rd.g1,current:!!rd.g1&&!rd.g2},{label:'Gate 2',on:!!rd.g2,current:!!rd.g2},{label:'Runfest',on:rd.g2==='green',current:false}];host.innerHTML=`<div class="coachHero coach-${msg.tone}"><div class="micro">RB Coach · dagens beskjed</div><h2>${msg.title}</h2><p>${msg.text}</p></div><div class="coachGrid"><div class="coachMini"><div class="micro">Uke ${r.w.n} · coach review</div><h3>${r.verdict}</h3><p>${r.review}</p><div class="coachStats"><span>${r.km.toFixed(1).replace('.0','')} / ${r.w.km} km</span><span>${r.q.length} kvalitet</span><span>${r.avgRpe?'RPE '+r.avgRpe:'RPE –'}</span></div><div class="coachFocus"><b>Neste fokus:</b> ${r.focus}</div></div><div class="coachMini"><div class="micro">1:23 · veien til grønt</div><div class="readinessLabel">${rd.label}</div><div class="readinessTrack">${steps.map(s=>`<div class="rStep ${s.on?'on':''} ${s.current?'current':''}"><span class="rDot"></span><span>${s.label}</span></div>`).join('')}</div><p>${rd.text}</p><div class="readinessNote">Gate 2 er den eneste testen som kan kvalifisere 1:23 fullt ut.</div></div></div>`;const out=document.getElementById('todayCoach');if(out)out.textContent=`${msg.title}. ${msg.text}`}
function install(){if(typeof renderDashboard==='function'&&!renderDashboard.__coachWrapped){const original=renderDashboard;const wrapped=function(){original();setTimeout(renderCoach,0)};wrapped.__coachWrapped=true;renderDashboard=wrapped}renderCoach();document.addEventListener('change',e=>{if(e.target.closest('.feedbackGrid')||e.target.id==='gate1'||e.target.id==='gate2'||e.target.matches('.checkline input'))setTimeout(renderCoach,0)})}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',install);else install();
})();
