/* RunnerBear v10.1 · Bakken Coach UI + decision-first polish */
(function(){
'use strict';
const $=id=>document.getElementById(id),qs=(s,r=document)=>r?.querySelector?.(s)||null,qsa=(s,r=document)=>[...(r?.querySelectorAll?.(s)||[])],esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=s=>{s=Math.max(0,Math.round(+s||0));const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${m}:${String(x).padStart(2,'0')}`},round=v=>Math.round(v*2)/2,localIso=d=>{const x=d instanceof Date?d:new Date(d),z=n=>String(n).padStart(2,'0');return`${x.getFullYear()}-${z(x.getMonth()+1)}-${z(x.getDate())}`};
function engine(){return window.RunnerBearCoachEngine}
function selectedDate(){const stored=sessionStorage.getItem('runnerbear_v92_plan_day')||'';if(/^\d{4}-\d{2}-\d{2}$/.test(stored))return stored;const card=qs('#weeks .day.rb31-selected')||qs('#weeks .day.open'),label=qs('.daydate',card)?.textContent?.trim();return engine()?.schedule().find(x=>x.label===label)?.ds||''}
function activityRow(x){const a=x.activity,z=engine().intensity(a),m=[];if(a.distance)m.push(`${(a.distance/1000).toFixed(1).replace('.0','')} km`);if(a.duration)m.push(fmt(a.duration));if(a.heartrate)m.push(`${Math.round(a.heartrate)} bpm`);const lab=x.kind==='alternative'?'ALTERNATIV':x.kind==='replacement'?'ERSTATNING':x.kind==='plan-candidate'?'AKTIVITET':'EKSTRA';return`<div class="rb100-activity-row"><div><span>${lab}</span><b>${esc(a.title||engine().sportName(a))}</b><small>${esc(engine().sportName(a))} · ${z.level==='easy'?'lett':z.level==='moderate'?'moderat':'hard'}</small></div><strong>${esc(m.join(' · ')||'registrert')}</strong></div>`}
function decoratePlan(){qsa('.rb100-extra-activities').forEach(x=>x.remove());const ds=selectedDate();if(!ds)return;const rows=engine().classified().filter(x=>x.activity.ds===ds&&x.kind!=='planned');if(!rows.length)return;const card=qs('#weeks .day.rb31-selected')||qs('#weeks .day.open'),body=qs('.day-body',card)||card;if(!body)return;const box=document.createElement('section');box.className='rb100-extra-activities';box.innerHTML=`<div class="rb100-minihead"><span>FAKTISK DAG</span><b>${rows.length} ${rows.length===1?'aktivitet':'aktiviteter'} utover automatisk match</b></div>${rows.map(activityRow).join('')}`;body.appendChild(box)}
function decorateToday(){qsa('.rb100-today-extra').forEach(x=>x.remove());const ds=localIso(new Date()),rows=engine().classified().filter(x=>x.activity.ds===ds&&x.kind==='extra');if(!rows.length)return;const host=qs('#rb35Today .rb35-workout')||$('todayCard');if(!host)return;const el=document.createElement('div');el.className='rb100-today-extra';el.innerHTML=`<span>EKSTRA REGISTRERT</span><b>${rows.map(x=>`${engine().sportName(x.activity)} ${x.activity.duration?fmt(x.activity.duration):''}`).join(' · ')}</b>`;host.appendChild(el)}
function enforceFlex(){const allowed=engine().flexLabels();qsa('#weeks .day').forEach(day=>{const label=qs('.daydate',day)?.textContent?.trim()||'';qsa('.easy-choice',day).forEach(box=>{if(!allowed.has(label))box.remove()})});const p=engine().schedule().find(x=>x.ds===localIso(new Date()));if(p&&!allowed.has(p.label))qsa('#today .easy-choice').forEach(x=>x.remove())}
function devHtml(){const e=engine(),pred=e.predictions(),th=e.thresholdHistory().at(-1),trend=e.thresholdTrend(),p=e.policy(),prof=p.profile,d=e.decision(),hist=e.thresholdHistory().slice(-5).reverse().map(x=>`<div><span>${esc(x.date)}</span><b>${esc(x.pace)}/km</b><small>${esc(x.hr)} bpm</small></div>`).join('');const c=x=>`<small>${x.confidence} sikkerhet</small>`;return`<article class="rb97-more-card rb100-development" id="rb100Development"><div class="rb97-more-head"><span>UTVIKLING</span><strong>LIVE MODELL</strong></div><div class="rb100-predictions"><div><span>5 KM</span><b>${fmt(pred.five.seconds)}</b>${c(pred.five)}</div><div><span>10 KM</span><b>${fmt(pred.ten.seconds)}</b>${c(pred.ten)}</div><div><span>HALVMARATON</span><b>${fmt(pred.half.seconds)}</b>${c(pred.half)}</div><div><span>MARATON</span><b>${fmt(pred.marathon.seconds)}</b>${c(pred.marathon)}</div></div><div class="rb100-threshold"><div><span>TERSKEL NÅ</span><b>${esc(th.pace)}/km · ${esc(th.hr)} bpm</b></div><p class="${trend.tone}">${esc(trend.text)}</p></div><div class="rb100-base"><span>LØPSBASE</span><b>~${round(p.anchorKm||prof.baseKm||50)} km/uke</b><small>Min ${+prof.minRunDays||5} løpedager · maks ${+prof.maxKm||55} km · ${+prof.flexibleSessions||2} fleksible økter.</small></div><details class="rb100-details"><summary>Se modellgrunnlag og treningsrammer <span>↓</span></summary><div class="rb100-model-note"><b>RB Coach · ${d.level==='green'?'grønn':d.level==='yellow'?'gul':'rød'}</b><p>${esc(d.message)}</p><small>${esc(pred.reason)}${pred.long?` · lengste løp siste 35 d ${round(pred.long)} km`:''}</small></div><div class="rb100-th-history">${hist}</div><form id="rb100Settings" class="rb100-settings"><label>Normal løpsuke<input name="baseKm" type="number" min="30" max="80" value="${+prof.baseKm||50}"></label><label>Maks løpsuke<input name="maxKm" type="number" min="35" max="90" value="${+prof.maxKm||55}"></label><label>Min. løpedager<input name="minRunDays" type="number" min="3" max="7" value="${+prof.minRunDays||5}"></label><label>Fleksible økter<input name="flexibleSessions" type="number" min="0" max="2" value="${+prof.flexibleSessions||2}"></label><label class="rb100-check"><input name="autoVolume" type="checkbox" ${prof.autoVolume!==false?'checked':''}> RunnerBear styrer volum automatisk</label><button type="submit">Lagre rammer</button></form></details></article>`}
function development(){const more=qs('#more .rb97-more-surface')||$('more');if(!more)return;const old=$('rb100Development'),w=document.createElement('div');w.innerHTML=devHtml();const fresh=w.firstElementChild;if(old)old.replaceWith(fresh);else{const grid=qs('.rb97-more-grid',more);grid?grid.insertAdjacentElement('afterend',fresh):more.prepend(fresh)}$('rb100Settings')?.addEventListener('submit',ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget),p={...engine().policy().profile,baseKm:+f.get('baseKm')||50,maxKm:+f.get('maxKm')||55,minRunDays:+f.get('minRunDays')||5,flexibleSessions:Math.min(2,+f.get('flexibleSessions')||0),autoVolume:!!f.get('autoVolume')};p.maxKm=Math.max(p.baseKm,p.maxKm);localStorage.setItem('runfest26_training_profile_v10',JSON.stringify(p));location.reload()})}
function policyNote(){const plan=$('plan');if(!plan)return;let n=$('rb100PolicyNote'),p=engine().policy(),r=p.normalRange||[48,52],prof=p.profile;if(!n){n=document.createElement('div');n.id='rb100PolicyNote';n.className='rb100-policy-note';qs('.section-head',plan)?.insertAdjacentElement('afterend',n)}n.innerHTML=`<span>RB COACH · VOLUM</span><b>${round(r[0])}–${round(r[1])} km normalt</b><small>maks ${+prof.maxKm||55} · min ${+prof.minRunDays||5} løpedager · ingen treningsgjeld</small>`}
function polishCountdown(){const c=qs('.topbar .race-count');if(!c||c.dataset.rb101==='1')return;const value=$('countdown')?.textContent||'–';c.dataset.rb101='1';c.innerHTML=`<span class="rb101-race-kicker">RUNFEST</span><div><strong><span id="countdown">${esc(value)}</span></strong><small>dager</small></div>`}
function polishToday(){const surface=qs('#rb35Today .rb35-surface');const greeting=qs('.rb35-greeting',surface);if(surface&&greeting&&surface.firstElementChild!==greeting)surface.prepend(greeting);qsa('#today article,#today section').forEach(el=>{if(el.closest('#rb35Today'))return;const head=(qs('.kicker span:first-child,.eyebrow,h2,h3',el)?.textContent||'').trim();if(/neste\s+økt/i.test(head))el.classList.add('rb101-hide-duplicate-next')})}
function polishPlan(){const overview=$('rb31PlanOverview');if(overview)overview.classList.add('rb101-plan-centered');const today=localIso(new Date());qsa('#rb31PlanOverview [data-rb31-day]').forEach(chip=>{const p=engine()?.schedule().find(x=>x.ds===today);const isToday=!!p&&(chip.dataset.rb31Day===p.label||chip.dataset.rb31Day===p.ds);chip.toggleAttribute('aria-current',isToday)})}
function openPlanOnToday(){const p=engine()?.schedule().find(x=>x.ds===localIso(new Date()));if(!p)return;setTimeout(()=>{const chip=qsa('#rb31PlanOverview [data-rb31-day]').find(x=>x.dataset.rb31Day===p.label||x.dataset.rb31Day===p.ds);chip?.click()},120)}
function style(){if($('rb100Style'))return;const s=document.createElement('style');s.id='rb100Style';s.textContent=`
.rb100-development{margin-top:14px}.rb100-predictions{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:14px 0}.rb100-predictions>div{padding:12px;border:1px solid var(--line);border-radius:12px;background:rgba(255,255,255,.025);display:grid;gap:3px}.rb100-predictions span,.rb100-base span,.rb100-threshold span,.rb100-minihead span,.rb100-today-extra span{font-size:8px;letter-spacing:.11em;color:var(--muted);font-weight:800}.rb100-predictions b{font-size:20px}.rb100-predictions small,.rb100-base small{font-size:9px;color:var(--muted)}.rb100-threshold{display:grid;grid-template-columns:auto 1fr;gap:14px;align-items:center;padding:12px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.rb100-threshold>div,.rb100-base{display:grid;gap:4px}.rb100-threshold p{margin:0;text-align:right;font-size:10px;color:var(--muted)}.rb100-threshold p.green{color:var(--green)}.rb100-threshold p.yellow{color:var(--yellow)}.rb100-base{padding:12px 0}.rb100-details summary{cursor:pointer;font-size:10px;font-weight:750}.rb100-model-note{padding:12px 0}.rb100-model-note p,.rb100-model-note small{font-size:9.5px;line-height:1.5;color:var(--muted)}.rb100-th-history>div{display:grid;grid-template-columns:1fr auto auto;gap:10px;font-size:9px;padding:7px 0;border-bottom:1px solid var(--line)}.rb100-settings{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;padding-top:10px}.rb100-settings label{display:grid;gap:4px;font-size:8px;color:var(--muted)}.rb100-settings input[type=number]{width:100%;box-sizing:border-box;padding:8px;border:1px solid var(--line);border-radius:8px;background:transparent;color:inherit}.rb100-settings .rb100-check,.rb100-settings button{grid-column:1/-1}.rb100-settings .rb100-check{display:flex;align-items:center;gap:7px}.rb100-settings button{padding:9px;border:1px solid var(--line);border-radius:9px;background:transparent;color:inherit}
.rb100-policy-note{margin:0 auto 12px!important;padding:8px 11px!important;border:1px solid var(--line)!important;border-radius:12px!important;display:flex!important;gap:8px!important;align-items:baseline!important;flex-wrap:wrap!important;max-width:100%!important;box-sizing:border-box!important;background:transparent!important;transform:none!important;left:auto!important}.rb100-policy-note span{font-size:7.5px;letter-spacing:.1em;color:var(--muted);font-weight:800}.rb100-policy-note b{font-size:10px}.rb100-policy-note small{font-size:9px;color:var(--muted)}
.rb100-extra-activities{margin-top:12px;padding-top:10px;border-top:1px solid var(--line)}.rb100-minihead{display:flex;justify-content:space-between;gap:8px;margin-bottom:7px}.rb100-minihead b{font-size:9px}.rb100-activity-row{display:flex;justify-content:space-between;gap:12px;padding:8px 0;border-top:1px solid rgba(255,255,255,.05)}.rb100-activity-row>div{display:grid;gap:2px}.rb100-activity-row span{font-size:8px;color:var(--muted);letter-spacing:.1em}.rb100-activity-row b,.rb100-activity-row strong{font-size:10px}.rb100-activity-row small{font-size:9px;color:var(--muted)}.rb100-today-extra{margin-top:10px;padding:9px 10px;border:1px solid var(--line);border-radius:10px;display:grid;gap:3px}.rb100-today-extra b{font-size:10px}
.rb101-hide-duplicate-next{display:none!important}.rb35-surface>.rb35-greeting:first-child{order:-10}
#plan #rb31PlanOverview,#plan .rb31-plan-overview,#plan .rb31-week-nav,#plan .rb31-day-map{width:100%!important;max-width:100%!important;box-sizing:border-box!important;margin-left:auto!important;margin-right:auto!important;transform:none!important;left:auto!important;right:auto!important}.rb31-plan-overview{overflow:hidden}.rb31-week-center{justify-items:center!important}.rb31-day-chip[aria-current="true"]{outline:2px solid rgba(63,112,77,.14);outline-offset:1px}
.topbar .race-count[data-rb101="1"]{display:flex!important;align-items:center!important;gap:9px!important;border:0!important;background:transparent!important;box-shadow:none!important;padding:0!important;min-width:auto!important;text-align:right!important}.rb101-race-kicker{font-size:7px!important;letter-spacing:.13em!important;font-weight:850!important;color:var(--muted)!important}.topbar .race-count[data-rb101="1"]>div{display:flex;align-items:baseline;gap:3px}.topbar .race-count[data-rb101="1"] strong{font-size:18px!important;line-height:1!important;letter-spacing:-.04em!important}.topbar .race-count[data-rb101="1"] small{font-size:8px!important;color:var(--muted)!important;font-weight:750!important}
@media(max-width:720px){.rb100-predictions{grid-template-columns:repeat(2,minmax(0,1fr))}.rb100-settings{grid-template-columns:repeat(2,minmax(0,1fr))}.rb100-threshold{grid-template-columns:1fr}.rb100-threshold p{text-align:left}.rb100-policy-note{margin-top:0!important}.rb100-policy-note small{display:none}.rb35-surface{padding-top:0!important}.rb35-greeting{margin-top:0!important;padding-top:0!important}#plan #rb31PlanOverview{margin-inline:0!important}.rb31-plan-overview{padding-left:13px!important;padding-right:13px!important}.rb31-day-map{gap:4px!important}.rb31-day-chip{min-width:0!important}.topbar .race-count[data-rb101="1"]{gap:6px!important}.rb101-race-kicker{display:none!important}.topbar .race-count[data-rb101="1"] strong{font-size:17px!important}.topbar .race-count[data-rb101="1"] small{font-size:7.5px!important}}
`;document.head.appendChild(s)}
function polish(){polishCountdown();polishToday();polishPlan()}
let queued=false;function render(){if(!engine())return;style();development();policyNote();enforceFlex();decoratePlan();decorateToday();polish()}function soon(){if(queued)return;queued=true;setTimeout(()=>{queued=false;render()},100)}function init(){render();setTimeout(render,350);setTimeout(render,1000);document.addEventListener('click',e=>{const nav=e.target.closest('.navbtn');if(nav?.dataset.tab==='plan')openPlanOnToday();if(e.target.closest('.navbtn,[data-rb31-day],[data-rb31-week],[data-rb97-sync],#rb94Sync,[data-mode]'))soon()},true);const roots=[$('plan'),$('today'),$('more')].filter(Boolean);roots.forEach(r=>{let q=false;new MutationObserver(()=>{if(q)return;q=true;setTimeout(()=>{q=false;if(!$('rb100Development'))development();if(!$('rb100PolicyNote'))policyNote();enforceFlex();decoratePlan();decorateToday();polish()},140)}).observe(r,{subtree:true,childList:true})})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
