const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {DatabaseSync}=require('node:sqlite');

const day=(value,offset)=>new Date(Date.parse(`${value}T12:00:00Z`)-offset*86400000).toISOString().slice(0,10);
const healthRows=(today,patch={})=>Array.from({length:22},(_,index)=>({date:day(today,index),hrv_ms:index===0?(patch.hrv??60):60,sleep_seconds:index===0?(patch.sleep??27000):27000,rhr_bpm:index===0?(patch.rhr??50):50,updated_at:`${today}T08:00:00Z`}));

test('one isolated low HRV signal is watch-only and never increases dose',async()=>{
  const {buildBodyResponse}=await import('../cloud/runnerbear-cloud/src/v11/body-response.js'),today='2026-08-28',response=buildBodyResponse({healthRows:healthRows(today,{hrv:40}),syncedAt:`${today}T08:00:00Z`,todayWorkout:{workoutType:'quality'},now:`${today}T09:00:00Z`});
  assert.equal(response.state,'watch');assert.deepEqual(response.reasonCodes,['LOW_HRV']);assert.equal(response.recommendedAction.kind,'keep_with_margin');assert.equal(response.recommendedAction.reductionPercent,0);assert.equal(response.recommendedAction.maximumDose,'planned');assert.equal(response.domains.find(row=>row.id==='autonomic').vote,1);
});

test('two independent response domains produce one bounded downshift',async()=>{
  const {buildBodyResponse}=await import('../cloud/runnerbear-cloud/src/v11/body-response.js'),today='2026-08-28',response=buildBodyResponse({healthRows:healthRows(today,{hrv:40,sleep:19000}),syncedAt:`${today}T08:00:00Z`,todayWorkout:{workoutType:'quality'},now:`${today}T09:00:00Z`});
  assert.equal(response.state,'adjust');assert.equal(response.recommendedAction.kind,'reduce_repetitions');assert.equal(response.recommendedAction.reductionPercent,20);assert.ok(response.domains.filter(row=>row.vote===1).length>=2);assert.equal(response.recommendedAction.maximumDose,'planned');
});

test('three non-safety domains still produce one clear bounded adjustment',async()=>{
  const {buildBodyResponse}=await import('../cloud/runnerbear-cloud/src/v11/body-response.js'),today='2026-08-28',response=buildBodyResponse({healthRows:healthRows(today,{hrv:40,sleep:19000}),syncedAt:`${today}T08:00:00Z`,yesterdayLoad:{highCost:true,qualityCost:.9},todayWorkout:{workoutType:'quality'},now:`${today}T09:00:00Z`});
  assert.equal(response.domains.filter(row=>row.vote===1&&row.id!=='safety').length,3);assert.equal(response.state,'adjust');assert.equal(response.recommendedAction.kind,'reduce_repetitions');assert.equal(response.recommendedAction.reductionPercent,20);assert.equal(response.checkIn.required,false);
});

test('persistent autonomic deviation can downshift while good data never adds training',async()=>{
  const {buildBodyResponse}=await import('../cloud/runnerbear-cloud/src/v11/body-response.js'),today='2026-08-28',persistent=healthRows(today);persistent[0].hrv_ms=48;persistent[1].hrv_ms=49;const response=buildBodyResponse({healthRows:persistent,syncedAt:`${today}T08:00:00Z`,todayWorkout:{workoutType:'easy'},now:`${today}T09:00:00Z`}),positive=buildBodyResponse({healthRows:healthRows(today,{hrv:78,sleep:31000,rhr:44}),syncedAt:`${today}T08:00:00Z`,todayWorkout:{workoutType:'quality'},now:`${today}T09:00:00Z`});
  assert.equal(response.state,'adjust');assert.ok(response.reasonCodes.includes('PERSISTENT_LOW_HRV'));assert.equal(response.recommendedAction.reductionPercent,20);assert.equal(positive.state,'as_planned');assert.equal(positive.recommendedAction.kind,'keep');assert.equal(positive.recommendedAction.reductionPercent,0);
});

test('illness and missing data fail safely without a medical score',async()=>{
  const {buildBodyResponse}=await import('../cloud/runnerbear-cloud/src/v11/body-response.js'),today='2026-08-28',ill=buildBodyResponse({healthRows:healthRows(today),syncedAt:`${today}T08:00:00Z`,subjective:{state:'heavy',reasons:['illness']},todayWorkout:{workoutType:'quality'},now:`${today}T09:00:00Z`}),missing=buildBodyResponse({healthRows:[],todayWorkout:{workoutType:'easy'},now:`${today}T09:00:00Z`});
  assert.equal(ill.state,'recover');assert.ok(ill.reasonCodes.includes('ILLNESS'));assert.equal(ill.checkIn.required,true);assert.equal(ill.recommendedAction.kind,'needs_input');assert.equal(missing.state,'wait_for_data');assert.equal(missing.confidence,'low');assert.equal(Object.hasOwn(ill,'score'),false);
});

test('v11.1 migration is additive and installs provenance, baseline, response and check-in tables',()=>{
  const sql=fs.readFileSync('cloud/runnerbear-cloud/migrations/0007_body_response.sql','utf8'),db=new DatabaseSync(':memory:');for(const file of fs.readdirSync('cloud/runnerbear-cloud/migrations').sort())db.exec(fs.readFileSync(`cloud/runnerbear-cloud/migrations/${file}`,'utf8'));const names=db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name IN ('rb_health_observations','rb_health_baseline_snapshots','rb_body_response_snapshots','rb_subjective_checkins','rb_workout_response_links','rb_recovery_insights') ORDER BY name").all().map(row=>row.name);assert.equal(names.length,6);assert.doesNotMatch(sql,/DROP TABLE/i);assert.match(sql,/UNIQUE\(user_id,local_date,metric,source\)/);assert.match(sql,/CHECK\(state IN \('as_planned','watch','adjust','recover','wait_for_data'\)\)/);db.prepare("INSERT INTO rb_users(id,created_at,updated_at) VALUES('primary','2026-08-28T08:00:00Z','2026-08-28T08:00:00Z')").run();db.prepare("INSERT INTO rb_health_daily(user_id,date,hrv_ms,sleep_seconds,rhr_bpm,payload_json,updated_at) VALUES('primary','2026-08-28',60,27000,50,'{}','2026-08-28T08:00:00Z')").run();assert.deepEqual(db.prepare("SELECT DISTINCT source FROM rb_health_observations").all().map(row=>row.source),['tredict']);assert.equal(db.prepare("SELECT COUNT(*) AS n FROM rb_health_observations").get().n,3);db.prepare("UPDATE rb_health_daily SET hrv_ms=NULL,updated_at='2026-08-28T09:00:00Z' WHERE user_id='primary' AND date='2026-08-28'").run();assert.equal(db.prepare("SELECT COUNT(*) AS n FROM rb_health_observations WHERE metric='hrv'").get().n,0);assert.equal(db.prepare("SELECT COUNT(*) AS n FROM rb_health_observations").get().n,2);db.close();
});

class Statement{constructor(db,sql){this.db=db;this.sql=sql;this.values=[]}bind(...values){const next=new Statement(this.db,this.sql);next.values=values;return next}async run(){return this._run()}_run(){const result=this.db.sqlite.prepare(this.sql).run(...this.values);return{success:true,meta:{changes:Number(result.changes||0)}}}async first(){return this.db.sqlite.prepare(this.sql).get(...this.values)||null}async all(){return{success:true,results:this.db.sqlite.prepare(this.sql).all(...this.values)}}}
class LocalD1{constructor(){this.sqlite=new DatabaseSync(':memory:')}prepare(sql){return new Statement(this,sql)}async batch(statements){this.sqlite.exec('BEGIN IMMEDIATE');try{const out=statements.map(statement=>statement._run());this.sqlite.exec('COMMIT');return out}catch(error){this.sqlite.exec('ROLLBACK');throw error}}close(){this.sqlite.close()}}
const canonical=value=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().filter(key=>key!=='sourceHash'&&value[key]!==undefined).map(key=>[key,canonical(value[key])])):value;
async function hash(value){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(canonical(value))));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
const request=(path,{method='GET',body,key='v111-test'}={})=>new Request(`https://runnerbear.test${path}`,{method,headers:{...(body?{'content-type':'application/json'}:{}),...(key?{'Idempotency-Key':key}:{})},body:body?JSON.stringify(body):undefined});

test('bootstrap and idempotent check-in share one plan-revision-bound Body Response snapshot',async()=>{
  const {handleV1027}=await import('../cloud/runnerbear-cloud/src/v11/routes.js'),db=new LocalD1();for(const file of fs.readdirSync('cloud/runnerbear-cloud/migrations').sort())db.sqlite.exec(fs.readFileSync(`cloud/runnerbear-cloud/migrations/${file}`,'utf8'));const now=new Date(),today=now.toISOString().slice(0,10),weekday=(now.getUTCDay()+6)%7;db.sqlite.prepare("INSERT INTO rb_users(id,created_at,updated_at) VALUES('primary',?1,?1)").run(now.toISOString());const runDays=[...new Set([weekday,(weekday+1)%7,(weekday+2)%7,(weekday+3)%7,(weekday+4)%7])].sort(),input={timezone:'Europe/Oslo',profile:{baseKm:35},constraints:{runDays,qualityDays:runDays.slice(0,2),longRunDay:runDays.at(-1),alternativeDays:[0,1,2,3,4,5,6].filter(value=>!runDays.includes(value)),maxRunDays:5,weeklyKmCap:55},goal:{mode:'base',distance:'half',date:'',name:''},effectivePlan:[{workoutId:'v111-today',localDate:today,status:'scheduled',sport:'running',workoutType:'easy',title:'7 km rolig',plannedDistanceM:7000,explicitChoice:true}]};input.sourceHash=await hash(input);const env={DB:db,COACH_LOOP_KILL_SWITCH:'false'},call=req=>handleV1027(req,env,{userId:'primary',bodyJson:r=>r.json(),corsHeaders:{}});let response=await call(request('/api/v2/migration/commit',{method:'POST',body:input,key:'v111-migration'}));assert.equal(response.status,200);const migrated=await response.json(),stamp=now.toISOString();for(const flag of ['coach_loop_shadow','coach_loop_read','coach_loop_ui','coach_loop_write'])db.sqlite.prepare("INSERT INTO rb_feature_flags(user_id,flag,enabled,payload_json,updated_at) VALUES('primary',?,1,'{}',?)").run(flag,stamp);for(let offset=0;offset<16;offset++)db.sqlite.prepare("INSERT INTO rb_health_daily(user_id,date,hrv_ms,sleep_seconds,rhr_bpm,payload_json,updated_at) VALUES('primary',?,?,?,?, '{}',?)").run(day(today,offset),60,27000,50,stamp);db.sqlite.prepare("INSERT INTO rb_sync_sources(user_id,source,last_synced_at,status,detail_json,updated_at) VALUES('primary','garmin',?,'ok','{}',?)").run(stamp,stamp);
  response=await call(request('/api/v2/bootstrap?scope=home'));assert.equal(response.status,200);const bootstrap=await response.json();assert.equal(bootstrap.bodyResponse.version,'body-response-1');assert.equal(bootstrap.bodyResponse.planRevisionId,migrated.planRevisionId);assert.equal(bootstrap.schemaVersion,4);assert.equal(bootstrap.healthDataFreshness.status,'fresh');assert.equal(Object.hasOwn(bootstrap.bodyResponse,'coachInput'),false);
  const body={state:'tired',reasons:['fatigue'],sourceId:`body-checkin:${today}`,localDate:today,workoutId:bootstrap.todayWorkout.workoutId,planRevisionId:migrated.planRevisionId,responsePhase:'next_morning'};response=await call(request('/api/v2/check-ins',{method:'POST',body,key:body.sourceId}));assert.equal(response.status,200);const first=await response.json();assert.equal(first.idempotent,false);assert.equal(first.bodyResponse.planRevisionId,migrated.planRevisionId);response=await call(request('/api/v2/check-ins',{method:'POST',body,key:body.sourceId}));const replay=await response.json();assert.equal(replay.idempotent,true);assert.equal(replay.checkinId,first.checkinId);assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM rb_subjective_checkins').get().n,1);assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM rb_workout_response_links').get().n,1);response=await call(request('/api/v2/check-ins',{method:'POST',body:{...body,sourceId:'different'},key:'header-key'}));assert.equal(response.status,400);db.close();
});

test('Concept 1 UI keeps Body Response inside Today with accessible details and no health tab',()=>{
  const ui=fs.readFileSync('runnerbear-ui-v11-source.js','utf8'),css=fs.readFileSync('runnerbear-v111-body-response.css','utf8'),html=fs.readFileSync('index.html','utf8'),manifest=JSON.parse(fs.readFileSync('runnerbear-v11-assets.json','utf8')),workflow=fs.readFileSync('.github/workflows/runnerbear-cloud-deploy.yml','utf8'),healthGate=fs.readFileSync('scripts/verify-v116-health.mjs','utf8');assert.match(ui,/function bodyResponseDetailModalHtml/);assert.match(ui,/aria-labelledby="rb111BodyTitle"/);assert.match(ui,/Fem domener · maks én stemme hver/);assert.match(ui,/Ett lavt HRV-signal endrer ikke planen alene/);assert.match(ui,/body-checkin:\$\{updatedAt\}/);assert.match(ui,/b\.textContent='Lagrer …'/);assert.doesNotMatch(html,/data-tab="health"|>Helse<|>HRV</);assert.match(css,/locked Concept 1/);assert.match(css,/\.rb111-checkin button\{min-height:44px/);assert.match(css,/@media\(max-width:680px\)/);assert.ok(manifest.styles.includes('runnerbear-v111-body-response.css'));assert.match(workflow,/verify-v116-health\.mjs/);assert.match(healthGate,/x\.bodyResponseEngineVersion==='body-response-1'/);assert.match(healthGate,/x\.schemaVersion===4/);
});
