const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const day=require('../runnerbear-v123-running-day.js'),analysis=require('../runnerbear-v1012-analysis.js');
const workout={type:'quality',title:'6 × 6 min terskel',km:12,desc:'90 s rolig pause',detail:'Puls 150–163. 4:10–4:20/km'};
test('shorter threshold previews change repetitions, recovery and total together without changing intensity',()=>{
 const model=analysis.structuredWorkout(workout),before=JSON.stringify(workout),p=day.timeProposal({workout,model,minutes:45});assert.equal(p.patch.prescription.main.repetitions,2);assert.equal(p.patch.plannedDurationSeconds,2310);assert.equal(p.workReductionSeconds,1440);assert.equal(p.patch.prescription.main.recoverySeconds,90);assert.ok(p.patch.plannedDurationSeconds<=45*60);assert.equal(analysis.structuredWorkout(p.patch).interval.recoverySeconds,90);assert.match(p.patch.detail,/150–163/);assert.match(p.patch.detail,/4:10–4:20/);assert.equal(JSON.stringify(workout),before);
});
test('insufficient time, unsupported structures and already fitting workouts cannot silently replace a session',()=>{
 const model=analysis.structuredWorkout(workout);assert.ok(day.timeProposal({workout,model,minutes:30}).error);assert.ok(day.timeProposal({workout,model,minutes:25}).error);assert.ok(day.timeProposal({workout:{...workout,title:'10 × 400 m'},model,minutes:45}).error);assert.ok(day.timeProposal({workout:{...workout,plannedDurationSeconds:2400},model,minutes:45}).error);
 const p=day.timeProposal({workout:{type:'easy',km:10,plannedDurationSeconds:3600,title:'Rolig løp'},minutes:30});assert.equal(p.patch.plannedDurationSeconds,1800);assert.equal(p.patch.km,5);assert.equal(p.patch.prescription.main.seconds,1800);
});
const storage=()=>({getItem:()=>null,setItem(){},removeItem(){}});
function client(fetch){const window={RunnerBearV1026:require('../runnerbear-v1026-coach-loop.js'),addEventListener(){},dispatchEvent(){}};vm.runInNewContext(fs.readFileSync('runnerbear-cloud-v11.js','utf8'),{window,document:{documentElement:{classList:{remove(){},add(){},toggle(){}}},querySelector:()=>null},fetch,AbortController,CustomEvent:class{},localStorage:storage(),console:{warn(){},info(){},error(){}},setTimeout:()=>0,clearTimeout(){}});return window.RunnerBearCloudV11}
const data=()=>({ok:true,planRevisionId:'pr1',flags:{coach_loop_write:true},activePlan:{status:'active',planRevisionId:'pr1',items:[{workoutId:'w1',localDate:'2026-09-21',status:'scheduled',lockLevel:'none',workoutType:'quality',sport:'running',prescription:{main:{repetitions:6}}}]}});
test('preview is separate from commit, carries exact structure and rejects a stale revision',async()=>{
 const d=data(),requests=[],api=client(async(path,opts)=>{requests.push({path,opts});return{ok:true,json:async()=>opts.method==='POST'?{ok:true,previewId:'draft',expectedPlanRevisionId:'pr1',rows:JSON.parse(opts.body).items}:d}});await api.start();const patch=day.timeProposal({workout,model:analysis.structuredWorkout(workout),minutes:45}).patch,preview=await api.previewUserWorkout('w1',patch,'key');assert.equal(requests.filter(r=>r.path.includes('/commit')).length,0);assert.equal(preview.rows[0].prescription.main.repetitions,2);assert.equal(preview.rows[0].explicitChoice,true);assert.equal(d.activePlan.items[0].prescription.main.repetitions,6);api.snapshot().planRevisionId='pr2';await assert.rejects(api.commitUserWorkout(preview),/Planen har endret seg/);assert.equal(requests.length,2);
});
test('confirmed commit survives failed refresh and retains the authoritative saved plan',async()=>{
 let gets=0;const d=data(),keys=[],activePlan={...d.activePlan,planRevisionId:'pr2'};const api=client(async(path,opts)=>{if(opts.method==='POST'){keys.push(opts.headers['Idempotency-Key']);return{ok:true,json:async()=>({ok:true,planRevisionId:'pr2',activePlan})}}if(++gets>1)throw Error('offline');return{ok:true,json:async()=>d}});await api.start();const result=await api.commitUserWorkout({previewId:'draft',expectedPlanRevisionId:'pr1',key:'stable'});assert.equal(result.refreshPending,true);assert.equal(api.snapshot().planRevisionId,'pr2');assert.deepEqual(keys,['stable:commit']);
});
test('locked workout, disabled writes and failed commits never report a successful plan change',async()=>{
 const d=data(),api=client(async(path,opts)=>opts.method==='POST'?{ok:false,json:async()=>({message:'Lagring feilet'})}:{ok:true,json:async()=>d});await api.start();api.snapshot().activePlan.items[0].lockLevel='user';await assert.rejects(api.previewUserWorkout('w1',{},'k'),/låst/);await assert.rejects(api.commitUserWorkout({previewId:'draft',expectedPlanRevisionId:'pr1',key:'k'}),/Lagring feilet/);assert.equal(api.snapshot().planRevisionId,'pr1');api.snapshot().flags.coach_loop_write=false;await assert.rejects(api.previewUserWorkout('w1',{},'k'),/ikke tilgjengelige/);
});
