const {test,expect}=require('@playwright/test');
async function setup(page,width=390){
 await page.setViewportSize({width,height:844});await page.goto('/?fixture=preview');await page.locator('html.rb107-ready').waitFor();
 await page.evaluate(()=>{
  const ds=new Date().toLocaleDateString('sv-SE'),stamp=new Date().toISOString(),s=window.RunnerBearCloudV11.snapshot();s.flags={...s.flags,coach_loop_ui:false,coach_loop_write:false};s.oneDecision={...s.oneDecision,state:'follow',freshness:'current',generatedAt:stamp,validUntil:new Date(Date.now()+600000).toISOString(),safety:{planWritesByAi:false},primaryAction:{kind:'open_workout',label:'Se økten'}};s.recentActivities=[];
  window.RunnerBearCloudV11.snapshot=()=>s;window.RunnerBearPlanReadModel.get=()=>null;window.RunnerBearCoachEngine.schedule=()=>[{ds,type:'quality',title:'6 × 6 min terskel',km:12,desc:'90 s rolig pause',detail:'Puls 150–163. 4:10–4:20/km',week:1,label:'qa-quality'}];window.__writes=0;window.RunnerBearCloud.uploadLocal=async()=>{window.__writes++;if(window.__saveFail)throw Error('Forbindelsen er brutt');return{ok:true}};window.RunnerBearCoachOS.render();
 });
}
async function proposal(page){await page.locator('[data-rb123-adapt]').click();await page.locator('[data-rb126-reason="time"]').click();await page.locator('[data-rb126-minutes="45"]').click();await page.locator('[data-rb126-preview]').click();await expect(page.getByRole('heading',{name:'Se endringen før du velger'})).toBeVisible()}
test('preview can be cancelled, failed save is reversible and confirmed save updates the complete workout',async({page},info)=>{
 await setup(page);await proposal(page);await expect(page.locator('.rb126-compare')).toContainText('2 × 6 min terskel');expect(await page.evaluate(()=>window.__writes)).toBe(0);await page.screenshot({path:info.outputPath('adaptation-preview.png'),fullPage:true});
 await page.getByRole('button',{name:'Lukk øktdetaljer'}).click();expect(await page.evaluate(()=>localStorage.getItem('runfest26_week_adjustments'))).toBeNull();
 await proposal(page);await page.evaluate(()=>window.__saveFail=true);await page.locator('[data-rb126-apply]').click();await expect(page.getByRole('alert')).toContainText('ikke bekreftet');expect(await page.evaluate(()=>window.RunnerBearCoachOS.planFor(new Date().toLocaleDateString('sv-SE')).title)).toBe('6 × 6 min terskel');
 await page.evaluate(()=>window.__saveFail=false);await page.locator('[data-rb126-apply]').click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('#rb113DecisionTitle')).toHaveText('2 × 6 min terskel');await page.locator('[data-rb113-decision-action]').click();await expect(page.getByRole('dialog')).toContainText('15 min rolig oppvarming');await expect(page.getByRole('dialog')).toContainText('10 min rolig nedjogg');
});
test('an intervening revision invalidates the open preview',async({page})=>{
 await setup(page);await proposal(page);await page.evaluate(()=>localStorage.setItem('runnerbear_v10251_plan_revision','99'));await page.locator('[data-rb126-apply]').click();await expect(page.getByRole('alert')).toContainText('Planen eller datagrunnlaget er endret');expect(await page.evaluate(()=>window.__writes)).toBe(0);
});
for(const width of [320,390,430])test(`new photos, readable selected day and health/adaptation fit ${width}`,async({page},info)=>{
 await setup(page,width);const img=page.locator('.rb126-photo img').first();await expect(img).toBeVisible();expect(await img.evaluate(e=>Number(getComputedStyle(e).zIndex))).toBeGreaterThanOrEqual(0);await page.screenshot({path:info.outputPath('today.png'),fullPage:true});
 await proposal(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)).toBe(false);await page.screenshot({path:info.outputPath('adaptation.png'),fullPage:true});await page.getByRole('button',{name:'Lukk øktdetaljer'}).click();
 await page.locator('[data-rb111-body-open]').click();await expect(page.getByRole('heading',{name:'Helsebildet',exact:true})).toBeVisible();await page.locator('[data-rb126-health-range="28"]').click();await expect(page.locator('[data-rb126-health-range="28"]')).toHaveAttribute('aria-pressed','true');expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)).toBe(false);await page.screenshot({path:info.outputPath('health.png'),fullPage:true});
});
test('200 percent text keeps the daily action and adaptation readable on narrow mobile',async({page},info)=>{
 await setup(page,320);await page.evaluate(()=>{const sizes=[...document.querySelectorAll('#today *')].map(e=>[e,parseFloat(getComputedStyle(e).fontSize)]);for(const[e,size]of sizes)e.style.fontSize=size*2+'px'});expect(await page.locator('#today *:visible').evaluateAll(nodes=>nodes.filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({class:e.className,text:e.textContent.slice(0,40),right:e.getBoundingClientRect().right})))).toEqual([]);await expect(page.locator('[data-rb113-decision-action]')).toBeVisible();await page.screenshot({path:info.outputPath('text-200.png'),fullPage:true});
});
test('body check preserves an explicit symptom and does not confirm failed saving',async({page})=>{
 await setup(page);await page.evaluate(()=>{window.__beforeReadiness=JSON.stringify({[new Date().toLocaleDateString('sv-SE')]:{state:'fresh',reasons:[],choice:'pending'}});localStorage.setItem('runnerbear_v1022_daily_readiness',window.__beforeReadiness)});await page.locator('[data-rb111-body-open]').click();await expect(page.getByRole('dialog')).not.toContainText('Innenfor normalen');await page.locator('input[name="rb126-body-reason"][value="achilles"]').check();await page.evaluate(()=>window.__saveFail=true);await page.locator('[data-rb111-checkin="fresh"]').click();await expect(page.getByRole('dialog')).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('runnerbear_v1022_daily_readiness')===window.__beforeReadiness)).toBe(true);await page.evaluate(()=>window.__saveFail=false);await page.locator('[data-rb111-checkin="fresh"]').click();await expect(page.getByRole('dialog')).toHaveCount(0);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('runnerbear_v1022_daily_readiness'))[new Date().toLocaleDateString('sv-SE')]);expect(saved.reasons).toContain('achilles');expect(saved.state).toBe('tired');
});
