import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'runnerbear-v1021-assets.json'),'utf8'));
const join=(files,banner)=>banner+'\n'+files.map(file=>'/* canonical source: '+file+' */\n'+fs.readFileSync(path.join(root,file),'utf8').trim()+'\n').join('\n');
fs.writeFileSync(path.join(root,'runnerbear-core-v1021.js'),join(manifest.core,'/* RunnerBear 10.21 canonical core · generated by scripts/build-v1021.mjs */'),'utf8');
fs.writeFileSync(path.join(root,'runnerbear-data-v1021.js'),join(manifest.data,'/* RunnerBear 10.21 lazy Cloud/data runtime · generated by scripts/build-v1021.mjs */'),'utf8');
fs.writeFileSync(path.join(root,'runnerbear-v1021.css'),join(manifest.styles,'/* RunnerBear 10.21 canonical stylesheet · generated by scripts/build-v1021.mjs */'),'utf8');
console.log(JSON.stringify({core:manifest.core.length,data:manifest.data.length,styles:manifest.styles.length}));
