import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'runnerbear-v1022-assets.json'),'utf8'));
const join=(files,banner)=>banner+'\n'+files.map(file=>'/* canonical source: '+file+' */\n'+fs.readFileSync(path.join(root,file),'utf8').trim()+'\n').join('\n');
fs.writeFileSync(path.join(root,'runnerbear-core-v1022.js'),join(manifest.core,'/* RunnerBear 10.22 canonical core · generated by scripts/build-v1022.mjs */'),'utf8');
fs.writeFileSync(path.join(root,'runnerbear-ui-v1022.js'),'/* RunnerBear 10.22 canonical UI · generated by scripts/build-v1022.mjs */\n'+fs.readFileSync(path.join(root,manifest.ui),'utf8').trim()+'\n','utf8');
fs.writeFileSync(path.join(root,'runnerbear-data-v1022.js'),join(manifest.data,'/* RunnerBear 10.22 lazy Cloud/data runtime · generated by scripts/build-v1022.mjs */'),'utf8');
fs.writeFileSync(path.join(root,'runnerbear-v1022.css'),join(manifest.styles,'/* RunnerBear 10.22 canonical stylesheet · generated by scripts/build-v1022.mjs */'),'utf8');
console.log(JSON.stringify({core:manifest.core.length,ui:manifest.ui,data:manifest.data.length,styles:manifest.styles.length}));
