import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'runnerbear-v1026-assets.json'),'utf8'));
const join=(files,banner)=>banner+'\n'+files.map(file=>'/* canonical source: '+file+' */\n'+fs.readFileSync(path.join(root,file),'utf8').trim()+'\n').join('\n');
fs.writeFileSync(path.join(root,'runnerbear-core-v1026.js'),join(manifest.core,'/* RunnerBear 10.26.0 canonical core · generated by scripts/build-v1026.mjs */'),'utf8');
fs.writeFileSync(path.join(root,'runnerbear-ui-v1026.js'),'/* RunnerBear 10.26.0 canonical UI · generated by scripts/build-v1026.mjs */\n'+fs.readFileSync(path.join(root,manifest.ui),'utf8').trim()+'\n','utf8');
fs.writeFileSync(path.join(root,'runnerbear-data-v1026.js'),join(manifest.data,'/* RunnerBear 10.26.0 lazy Cloud/data runtime · generated by scripts/build-v1026.mjs */'),'utf8');
fs.writeFileSync(path.join(root,'runnerbear-v1026.css'),join(manifest.styles,'/* RunnerBear 10.26.0 canonical stylesheet · generated by scripts/build-v1026.mjs */'),'utf8');
console.log(JSON.stringify({build:manifest.build,core:manifest.core.length,ui:manifest.ui,data:manifest.data.length,styles:manifest.styles.length}));
