import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'runnerbear-v11-assets.json'),'utf8'));
const join=(files,banner)=>banner+'\n'+files.map(file=>'/* canonical source: '+file+' */\n'+fs.readFileSync(path.join(root,file),'utf8').trim()+'\n').join('\n');
fs.writeFileSync(path.join(root,'runnerbear-core-v11.js'),join(manifest.core,`/* RunnerBear ${manifest.build} canonical core · generated by scripts/build-v11.mjs */`),'utf8');
fs.writeFileSync(path.join(root,'runnerbear-ui-v11.js'),`/* RunnerBear ${manifest.build} canonical UI · generated by scripts/build-v11.mjs */\n`+fs.readFileSync(path.join(root,manifest.ui),'utf8').trim()+'\n','utf8');
fs.writeFileSync(path.join(root,'runnerbear-data-v11.js'),join(manifest.data,`/* RunnerBear ${manifest.build} lazy Cloud/data runtime · generated by scripts/build-v11.mjs */`),'utf8');
fs.writeFileSync(path.join(root,'runnerbear-v11.css'),join(manifest.styles,`/* RunnerBear ${manifest.build} canonical stylesheet · generated by scripts/build-v11.mjs */`),'utf8');
console.log(JSON.stringify({build:manifest.build,core:manifest.core.length,ui:manifest.ui,data:manifest.data.length,styles:manifest.styles.length}));
