const DAY_MS=86400000;
export const BAKKEN_ENGINE_VERSION='11.7.0';
export const BAKKEN_WORKOUT_BANK_VERSION='2.0.0';
export const BAKKEN_POLICY=Object.freeze({avoidHillWorkouts:true,repeatWindowDays:14});
const clean=value=>String(value??'').replace(/\s+/g,' ').trim();
const dateOnly=value=>/^\d{4}-\d{2}-\d{2}$/.test(String(value||'').slice(0,10))?String(value).slice(0,10):'';
const dayDistance=(a,b)=>Math.abs((Date.parse(`${dateOnly(a)}T12:00:00Z`)-Date.parse(`${dateOnly(b)}T12:00:00Z`))/DAY_MS);
const addDays=(value,days)=>new Date(Date.parse(`${dateOnly(value)}T12:00:00Z`)+days*DAY_MS).toISOString().slice(0,10);
const monday=value=>{const date=new Date(`${dateOnly(value)}T12:00:00Z`),day=(date.getUTCDay()+6)%7;date.setUTCDate(date.getUTCDate()-day);return date.toISOString().slice(0,10)};
const weekOrdinal=value=>Math.round((Date.parse(`${monday(value)}T12:00:00Z`)-Date.parse('2026-01-05T12:00:00Z'))/(7*DAY_MS));
const clone=value=>JSON.parse(JSON.stringify(value));
const terminal=row=>['completed','cancelled','replaced','skipped'].includes(String(row?.status||''));
const isQuality=row=>row?.workoutType==='quality'&&row?.sport==='running'&&!terminal(row);
const eventPayload=row=>row?.payload&&typeof row.payload==='object'?row.payload:{};
const eventId=row=>String(row?.event_id||row?.eventId||row?.source_id||row?.sourceId||'');
const hillPattern=/\b(?:hill|hills|hill repeats)\b|bakkeintervall|bakkeøkt|motbakkeintervall/i;

const session=(id,family,stimulus,title,workMinutes,cost,phases,main,desc,detail,purpose,extra={})=>Object.freeze({id,sessionId:id,family,stimulus,title,type:'quality',workMinutes,cost,phases,main,desc,detail,purpose,availability:'core',role:family,...extra});

export const QUALITY_LIBRARY=Object.freeze([
  session('threshold-6x6','threshold_long','threshold','6 × 6 min terskel',36,2,['BASE','BUILD','SPECIFIC'],{kind:'intervals',repetitions:6,workSeconds:360,recoverySeconds:90},'6 × 6 min kontrollert terskel med 90 sek rolig jogg.','Repeterbar fart og stabil pust. Ingen jakt på sluttpuls; avslutt før terskel blir X.','Bygge repeterbar terskelkapasitet med moderat muskulær kostnad.',{group:'main_threshold',km:12}),
  session('threshold-4x8','threshold_long','threshold','4 × 8 min terskel',32,2,['BASE','BUILD','SPECIFIC'],{kind:'intervals',repetitions:4,workSeconds:480,recoverySeconds:180},'4 × 8 min kontrollert terskel med 3 min rolig jogg.','Kontrollert og repeterbar fart. Ingen jakt på sluttpuls eller progressiv avslutning.','Gi en tydelig hovedterskel med god kontroll og håndterbar totaldose.',{group:'main_threshold',km:12}),
  session('threshold-3x10','threshold_long','threshold','3 × 10 min terskel',30,2,['BASE','BUILD','SPECIFIC'],{kind:'intervals',repetitions:3,workSeconds:600,recoverySeconds:120},'3 × 10 min kontrollert terskel med 2 min rolig jogg.','Normal dose i 10-minuttersfamilien. Hold samme tekniske uttrykk gjennom siste drag.','Bygge varighet nær terskel med normal og repeterbar dose.',{group:'main_threshold',doseFamily:'threshold_10min_family',dose:'moderate',km:12}),
  session('threshold-4x10','threshold_long','threshold','4 × 10 min terskel',40,3,['BUILD','SPECIFIC'],{kind:'intervals',repetitions:4,workSeconds:600,recoverySeconds:90},'4 × 10 min kontrollert terskel med 90 sek rolig jogg.','Høy dose i 10-minuttersfamilien. Brukes bare når responsbildet og belastningen er grønne.','Bygge terskelrobusthet med høy dose når positiv BUILD-respons støtter det.',{group:'main_threshold',doseFamily:'threshold_10min_family',dose:'high',requiresPositiveResponse:true,km:13}),
  session('threshold-4x2000','threshold_long','threshold','4 × 2000 m terskel',34,2,['BUILD','SPECIFIC'],{kind:'intervals',repetitions:4,workMeters:2000,recoverySeconds:90},'4 × 2000 m kontrollert terskel med 90 sek rolig jogg.','Farten styres av intern belastning. Siste drag skal være like kontrollert som det første.','Koble terskelkontroll til lengre, løpsnære drag.',{group:'main_threshold',availability:'specialist',km:12}),
  session('threshold-6x5','threshold_short','threshold','6 × 5 min terskel',30,2,['BASE','BUILD','SPECIFIC'],{kind:'intervals',repetitions:6,workSeconds:300,recoverySeconds:45},'6 × 5 min kontrollert terskel med 45 sek rolig jogg.','Kort pause krever kontrollert, repeterbar fart. Avslutt før økten blir X.','Gi en sentral støtteterskel med mye kontrollert arbeid og korte avbrekk.',{group:'support_threshold',km:11}),
  session('threshold-10x3','threshold_short','threshold','10 × 3 min terskel',30,2,['BASE','BUILD','SPECIFIC'],{kind:'intervals',repetitions:10,workSeconds:180,recoverySeconds:60},'10 × 3 min kontrollert terskel med 60 sek rolig jogg.','Hold igjen tidlig og bevar rytmen. Ingen jakt på høyest mulig puls.','Gi en repeterbar støttekvalitet med kortere drag.',{group:'support_threshold',km:11}),
  session('threshold-15x1','threshold_short','threshold','15 × 1 min / 30 sek',15,1,['BASE','BUILD','SPECIFIC'],{kind:'intervals',repetitions:15,workSeconds:60,recoverySeconds:30},'15 × 1 min kontrollert terskel med 30 sek rolig flyt.','Lavkost terskel: kort steg, god rytme og tydelig reserve.','Bevare terskelstimulus når coachen ønsker lavere total belastning.',{group:'support_threshold',dose:'low',km:9}),
  session('x-20x45-15','controlled_x','x','20 × 45/15 · kontrollert X',15,2,['BASE','BUILD','SPECIFIC'],{kind:'intervals',repetitions:20,workSeconds:45,recoverySeconds:15},'20 × 45 sek kontrollert X med 15 sek flytende pause.','Høyere aerob intensitet enn terskel, men aldri sprint eller all-out. Bevar teknikken.','Gi et moderat X-stimulus når full 30-repetisjonsdose ikke er nødvendig.',{group:'x',doseFamily:'x_45_15_family',dose:'moderate',km:9}),
  session('x-30x45-15','controlled_x','x','30 × 45/15 · full kontrollert X',22.5,3,['BUILD','SPECIFIC'],{kind:'intervals',repetitions:30,workSeconds:45,recoverySeconds:15},'30 × 45 sek kontrollert X med 15 sek flytende pause.','Full X-dose med bevart teknikk. Ikke sprint, ikke all-out og ingen sluttspurtkrav.','Gi full 45/15-dose når respons, fase og avstand til neste belastning støtter det.',{group:'x',doseFamily:'x_45_15_family',dose:'full',requiresPositiveResponse:true,km:11}),
  session('x-6x3','controlled_x','x','6 × 3 min · kontrollert X / VO₂',18,3,['BUILD','SPECIFIC'],{kind:'intervals',repetitions:6,workSeconds:180,recoverySeconds:90},'6 × 3 min kontrollert X med 90 sek rolig jogg.','Tydelig over terskel, men kontrollert: bevart teknikk, ikke sprint og ikke all-out.','Gi et selektivt høyere aerobt stimulus uten hero-fart.',{group:'x',km:10}),
  session('x-8x2','controlled_x','x','8 × 2 min · kontrollert X',16,2,['BUILD','SPECIFIC'],{kind:'intervals',repetitions:8,workSeconds:120,recoverySeconds:60},'8 × 2 min kontrollert X med 60 sek rolig jogg.','Raskt, men aldri all-out. Avslutt med reserve og bevart teknikk.','Tilby et spesialistalternativ når coachkonteksten tilsier korte X-drag.',{group:'x',availability:'specialist',km:10}),
  session('x-5x1000','vo2','x','5 × 1000 m · kontrollert VO₂',18,3,['SPECIFIC'],{kind:'intervals',repetitions:5,workMeters:1000,recoverySeconds:120},'5 × 1000 m kontrollert VO₂ med 2 min rolig jogg.','Sjeldent og målrettet. Kontrollert, ikke all-out, med terskelanker i uken.','Gi målrettet VO₂-stimulans for 5 km/10 km i SPECIFIC-fase.',{group:'x',availability:'specialist',goals:['five','ten'],requiresPositiveResponse:true,km:10}),
  session('specific-half-3x3000','race_specific','race_specific','3 × 3000 m · kontrollert HM-rytme',34,2,['SPECIFIC'],{kind:'intervals',repetitions:3,workMeters:3000,recoverySeconds:120},'3 × 3000 m rundt kontrollert halvmaratonrytme med 2 min rolig jogg.','Spesifikk trening, ikke en formtest. Avslutt med kontroll.','Koble terskelkapasiteten til aktivt halvmaratonmål.',{group:'race_specific',availability:'specialist',goals:['half'],km:13}),
  session('specific-ten-4x1600','race_specific','race_specific','4 × 1600 m · kontrollert 10 km-rytme',24,2,['SPECIFIC'],{kind:'intervals',repetitions:4,workMeters:1600,recoverySeconds:90},'4 × 1600 m kontrollert rundt 10 km-rytme.','Jevn fart og teknisk kontroll. Ingen sluttspurt.','Koble terskelarbeidet til aktivt 10 km-mål.',{group:'race_specific',availability:'specialist',goals:['ten'],km:11}),
  session('specific-five-10x600','race_specific','race_specific','10 × 600 m · kontrollert 5 km-rytme',20,2,['SPECIFIC'],{kind:'intervals',repetitions:10,workMeters:600,recoverySeconds:75},'10 × 600 m kontrollert rundt 5 km-rytme.','God rytme og reserve. Dette skal ikke bli en maksimal VO₂-test.','Gjøre terskelgrunnlaget relevant for aktivt 5 km-mål.',{group:'race_specific',availability:'specialist',goals:['five'],km:10}),
  session('taper-4x5','taper_threshold','threshold','4 × 5 min terskel · redusert dose',20,1,['TAPER','RACE','TRANSITION'],{kind:'intervals',repetitions:4,workSeconds:300,recoverySeconds:90},'4 × 5 min kontrollert terskel med god margin.','Bevar rytmen og avslutt mens beina fortsatt kjennes lette.','Bevare terskelfølelse og friskhet inn mot løp.',{group:'reduced',availability:'taper',km:8}),
  session('taper-3x6','taper_threshold','threshold','3 × 6 min terskel · redusert dose',18,1,['TAPER','RACE','TRANSITION'],{kind:'intervals',repetitions:3,workSeconds:360,recoverySeconds:120},'3 × 6 min kontrollert terskel med full reserve.','Kort totaldose, jevn pust og lett steg. Ingen progressiv avslutning.','Bevare terskelkontroll med lav total kostnad inn mot løp.',{group:'reduced',availability:'taper',km:8}),
  session('taper-5x3','taper_threshold','threshold','5 × 3 min terskel · lett rytme',15,1,['TAPER','RACE','TRANSITION'],{kind:'intervals',repetitions:5,workSeconds:180,recoverySeconds:75},'5 × 3 min kontrollert terskel med lett rytme.','Avslutt med mer å gå på. Økten skal gi spenst, ikke tretthet.','Vedlikeholde rytme og løpsøkonomi uten å bygge restitusjonsbehov.',{group:'reduced',availability:'taper',km:8}),
  session('taper-8x2','taper_threshold','threshold','8 × 2 min terskel · lett flyt',16,1,['TAPER','RACE','TRANSITION'],{kind:'intervals',repetitions:8,workSeconds:120,recoverySeconds:60},'8 × 2 min kontrollert terskel med rolig jogg.','Lett frekvens og tydelig kontroll. Ikke la korte drag bli X-belastning.','Bevare lett terskelflyt med minimal kostnad.',{group:'reduced',availability:'taper',km:8})
]);

export const ACTIVE_WORKOUT_BANK_IDS=Object.freeze(QUALITY_LIBRARY.map(row=>row.id));
const byId=id=>QUALITY_LIBRARY.find(row=>row.id===id)||null;
export const isExplicitHillWorkout=row=>hillPattern.test(`${row?.plannedLoad?.bakken?.sessionId||''} ${row?.prescription?.bakken?.sessionId||''} ${row?.title||''} ${row?.prescription?.legacy?.desc||''} ${row?.prescription?.legacy?.detail||''}`);

export function phaseFor(config={},referenceDate=new Date().toISOString().slice(0,10)){
  const goal=config.goal||{};if(goal.mode==='transition')return'TRANSITION';if(goal.mode==='base'||!dateOnly(goal.date))return'BASE';
  const activeRaces=[...(goal.secondary||[]).filter(row=>row.status!=='cancelled'&&dateOnly(row.date)>=referenceDate).map(row=>({date:dateOnly(row.date),effort:row.effort||'controlled'})),{date:dateOnly(goal.date),effort:'race'}].filter(row=>row.date).sort((a,b)=>a.date.localeCompare(b.date));
  const next=activeRaces[0],days=next?Math.round((Date.parse(`${next.date}T12:00:00Z`)-Date.parse(`${referenceDate}T12:00:00Z`))/DAY_MS):999;if(days<=7)return'RACE';if(days<=14)return'TAPER';if(days<=56)return'SPECIFIC';if(days<=112)return'BUILD';return'BASE';
}

function desiredFamily({phase,slot,week,goalDistance='half',hasRace=false,expectedQuality=2,responseMode='NORMAL'}={}){
  if(responseMode==='RECOVERY')return'taper_threshold';if(responseMode==='REDUCE'||responseMode==='HOLD')return'threshold_short';if(hasRace||expectedQuality<=1||phase==='TAPER'||phase==='RACE'||phase==='TRANSITION')return'taper_threshold';if(slot===0)return'threshold_long';const ordinal=Math.abs(weekOrdinal(week));if(phase==='BASE')return ordinal%3===0?'controlled_x':'threshold_short';if(phase==='BUILD')return ordinal%2===0?'controlled_x':'threshold_short';if(phase==='SPECIFIC')return ordinal%2===0?'race_specific':'controlled_x';return goalDistance==='half'?'threshold_short':'controlled_x';
}

function eligible(candidate,{family,phase,goalDistance,responseMode,slot=0}={}){
  if(isExplicitHillWorkout(candidate)||!candidate.phases.includes(phase)||candidate.goals&&!candidate.goals.includes(goalDistance)||slot===0&&candidate.stimulus!=='threshold'||['HOLD','REDUCE','RECOVERY'].includes(responseMode)&&candidate.stimulus!=='threshold'||candidate.requiresPositiveResponse&&!['NORMAL','BUILD'].includes(responseMode))return false;
  if(candidate.id==='threshold-4x10'&&responseMode!=='BUILD')return false;if(candidate.id==='x-30x45-15'&&phase!=='BUILD'&&phase!=='SPECIFIC')return false;if(candidate.id==='x-5x1000'&&(family!=='race_specific'&&family!=='controlled_x'||phase!=='SPECIFIC'))return false;return true;
}

function candidateScore(candidate,{family,phase,goalDistance,responseMode,date,history=[],slot=0}={}){
  if(!eligible(candidate,{family,phase,goalDistance,responseMode,slot}))return-1000;let score=candidate.family===family?100:candidate.stimulus==='threshold'&&family!=='controlled_x'&&family!=='race_specific'?42:0;if(candidate.availability==='specialist')score-=family==='race_specific'?20:72;if(responseMode==='REDUCE')score-=candidate.cost*28;if(responseMode==='BUILD')score+=candidate.workMinutes>=24?8:0;if(candidate.id==='threshold-3x10'&&responseMode!=='BUILD')score+=18;if(candidate.id==='threshold-4x10'&&responseMode==='BUILD')score+=20;if(candidate.id==='x-20x45-15')score+=responseMode==='NORMAL'?18:6;if(candidate.id==='x-30x45-15')score+=responseMode==='BUILD'?26:-6;if(candidate.id==='x-6x3')score-=8;
  const repeats=history.filter(row=>row.sessionId===candidate.id&&row.localDate<date).map(row=>dayDistance(row.localDate,date));if(repeats.some(days=>days<14))score-=90;else if(repeats.some(days=>days<28))score-=18;const familyRows=QUALITY_LIBRARY.filter(row=>row.family===family&&row.availability==='core'),rotation=Math.abs(weekOrdinal(date)+slot)%Math.max(1,familyRows.length),familyIndex=familyRows.findIndex(row=>row.id===candidate.id);if(familyIndex===rotation)score+=12;return score;
}

export function sessionHistory(items=[]){return items.map(row=>({localDate:dateOnly(row.localDate||row.ds),sessionId:String(row.plannedLoad?.bakken?.sessionId||row.prescription?.bakken?.sessionId||''),stimulus:String(row.plannedLoad?.bakken?.stimulus||row.intent||'')})).filter(row=>row.localDate&&row.sessionId)}

export function selectQualitySession({date,slot=0,week=monday(date),config={},history=[],expectedQuality=2,hasRace=false,responseMode='NORMAL',excludeIds=[]}={}){
  const phase=phaseFor(config,date),goalDistance=config.goal?.distance||'half',family=desiredFamily({phase,slot,week,goalDistance,hasRace,expectedQuality,responseMode}),excluded=new Set(excludeIds),ranked=QUALITY_LIBRARY.filter(row=>!excluded.has(row.id)).map(candidate=>({candidate,score:candidateScore(candidate,{family,phase,goalDistance,responseMode,date,history,slot})})).filter(row=>row.score>-1000).sort((a,b)=>b.score-a.score||a.candidate.cost-b.candidate.cost||a.candidate.id.localeCompare(b.candidate.id)),fallback=byId(['HOLD','REDUCE','RECOVERY'].includes(responseMode)?'threshold-15x1':'threshold-6x6'),selected=ranked[0]?.candidate||fallback;
  return{session:clone(selected),phase,family,responseMode,confidence:ranked[0]?.score>=80?'high':'medium',reasonCodes:[`PHASE_${phase}`,`ROLE_${family.toUpperCase()}`,`RESPONSE_${responseMode}`],rationale:`${phase==='SPECIFIC'?'Løpsspesifikk fase':'Bakken-grunnmotor'}: ${selected.purpose}`};
}

export function applyBakkenSession(row,selection,{evidenceId='',reasonCodes=[]}={}){
  const source=clone(row),session=selection.session,responseMode=selection.responseMode||'NORMAL',bakken={engineVersion:BAKKEN_ENGINE_VERSION,workoutBankVersion:BAKKEN_WORKOUT_BANK_VERSION,sessionId:session.id,family:session.family,stimulus:session.stimulus,phase:selection.phase,role:selection.family,responseMode,rationale:selection.rationale,confidence:selection.confidence,reasonCodes:[...new Set([...(selection.reasonCodes||[]),...reasonCodes])],evidenceId:evidenceId||undefined,workMinutes:session.workMinutes,cost:session.cost,repeatWindowDays:BAKKEN_POLICY.repeatWindowDays};
  return{...source,workoutType:'quality',sport:'running',title:session.title,intent:session.stimulus,source:'runnerbear-v11.7',prescription:{version:2,main:clone(session.main),bakken:{...bakken,purpose:session.purpose,guardrail:session.detail},legacy:{...(source.prescription?.legacy||{}),desc:session.desc,detail:session.detail}},plannedLoad:{...(source.plannedLoad||{}),bakken}};
}

export function programQualityWeek({rows=[],allItems=[],config={},week='',expectedQuality=2,responseMode='NORMAL'}={}){
  const dateWeek=week||monday(rows[0]?.localDate),qualityRows=rows.filter(isQuality).sort((a,b)=>a.localDate.localeCompare(b.localDate)),hasRace=rows.some(row=>row.workoutType==='race'),history=sessionHistory([...allItems,...rows]),selectedIds=[],replacements=new Map();qualityRows.forEach((row,slot)=>{const alreadyCurrent=row.plannedLoad?.bakken?.engineVersion===BAKKEN_ENGINE_VERSION&&row.plannedLoad?.bakken?.workoutBankVersion===BAKKEN_WORKOUT_BANK_VERSION&&!isExplicitHillWorkout(row),manualId=String(row.plannedLoad?.manualQualityChoice?.sessionId||''),manual=byId(manualId);if(manual&&!isExplicitHillWorkout(manual)){const phase=phaseFor(config,row.localDate),selection={session:clone(manual),phase,family:manual.family,responseMode:'NORMAL',confidence:'high',reasonCodes:[`PHASE_${phase}`,'MANUAL_WORKOUT_BANK_CHOICE'],rationale:`Valgt fra RunnerBear Workout Bank 2.0: ${manual.purpose}`};selectedIds.push(manual.id);replacements.set(row.workoutId,applyBakkenSession(row,selection,{reasonCodes:['EXPLICIT_CHOICE']}));return}if((row.lockLevel==='user'||row.lockLevel==='system'||row.explicitChoice===true||row.plannedLoad?.manualMove===true)&&alreadyCurrent)return;const selection=selectQualitySession({date:row.localDate,slot,week:dateWeek,config,history:[...history,...selectedIds.map((sessionId,index)=>({sessionId,localDate:qualityRows[index]?.localDate||row.localDate}))],expectedQuality,hasRace,responseMode,excludeIds:selectedIds});selectedIds.push(selection.session.id);replacements.set(row.workoutId,applyBakkenSession(row,selection,{reasonCodes:['WORKOUT_BANK_2']}))});return rows.map(row=>replacements.get(row.workoutId)||row);
}

export function repairFutureWorkoutBank({items=[],config={},today=new Date().toISOString().slice(0,10)}={}){
  const future=items.filter(row=>row.localDate>=today&&isQuality(row)),byWeek=new Map();for(const row of future){const key=monday(row.localDate);byWeek.set(key,[...(byWeek.get(key)||[]),row])}const replacements=new Map(),history=sessionHistory(items.filter(row=>row.localDate<today));for(const [week,rows] of byWeek){const ordered=rows.sort((a,b)=>a.localDate.localeCompare(b.localDate)),hasRace=items.some(row=>row.localDate>=week&&row.localDate<=addDays(week,6)&&row.workoutType==='race'),selectedIds=[];ordered.forEach((row,slot)=>{const id=String(row.plannedLoad?.bakken?.sessionId||row.prescription?.bakken?.sessionId||''),valid=ACTIVE_WORKOUT_BANK_IDS.includes(id)&&row.plannedLoad?.bakken?.engineVersion===BAKKEN_ENGINE_VERSION&&row.plannedLoad?.bakken?.workoutBankVersion===BAKKEN_WORKOUT_BANK_VERSION&&!isExplicitHillWorkout(row);if(valid){selectedIds.push(id);return}const selection=selectQualitySession({date:row.localDate,slot,week,config,history:[...history,...selectedIds.map((sessionId,index)=>({sessionId,localDate:ordered[index]?.localDate||row.localDate}))],expectedQuality:ordered.length,hasRace,responseMode:'NORMAL',excludeIds:selectedIds});selectedIds.push(selection.session.id);replacements.set(row.workoutId,applyBakkenSession(row,selection,{reasonCodes:[isExplicitHillWorkout(row)?'NO_HILL_POLICY':'WORKOUT_BANK_2_REPAIR']}))})}return{rows:items.map(row=>replacements.get(row.workoutId)||row),changedIds:[...replacements.keys()]};
}

export function responseSignal({items=[],events=[],today=new Date().toISOString().slice(0,10)}={}){
  const qualityItems=new Map(items.filter(row=>row.workoutType==='quality').map(row=>[String(row.workoutId),row])),cutoff=addDays(today,-10),relevant=events.filter(row=>String(row.event_type||row.eventType)==='feedback:workout').map(row=>({row,payload:eventPayload(row),date:dateOnly(eventPayload(row).responseDate||row.local_date||row.localDate||row.occurred_at)})).filter(entry=>entry.date>=cutoff&&entry.date<=today&&(qualityItems.has(String(entry.payload.workoutId||''))||[...qualityItems.values()].some(item=>item.localDate===dateOnly(entry.row.local_date||entry.row.localDate)))).sort((a,b)=>String(a.row.occurred_at||a.row.occurredAt||'').localeCompare(String(b.row.occurred_at||b.row.occurredAt||'')));const latest=relevant.at(-1);if(!latest)return null;const payload=latest.payload,rpe=Number(payload.rpe||0),pain=Number(payload.pain||0),control=clean(payload.control).toLowerCase();let mode='NORMAL',reasonCodes=['QUALITY_RESPONSE'];if(payload.illness===true||pain>=3){mode='RECOVERY';reasonCodes.push(payload.illness===true?'ILLNESS':'PAIN')}else if(control==='uncontrolled'||rpe>=9||payload.pain_increased===true){mode='REDUCE';reasonCodes.push('HIGH_SESSION_COST')}else if(control==='borderline'||rpe>=8||pain>0||payload.poor_sleep===true||payload.stress===true){mode='HOLD';reasonCodes.push('HOLD_RESPONSE')}else{const controlledWorkouts=new Set(relevant.filter(entry=>entry.payload.control==='controlled'&&Number(entry.payload.rpe||6)<=7&&Number(entry.payload.pain||0)===0).map(entry=>String(entry.payload.workoutId||entry.date)));if(controlledWorkouts.size>=2){mode='BUILD';reasonCodes.push('REPEATABLE_RESPONSE')}}const workout=qualityItems.get(String(payload.workoutId||''))||[...qualityItems.values()].find(item=>item.localDate===dateOnly(latest.row.local_date||latest.row.localDate));return{mode,eventId:eventId(latest.row),workoutId:workout?.workoutId||String(payload.workoutId||''),localDate:workout?.localDate||dateOnly(latest.row.local_date||latest.row.localDate),reasonCodes,confidence:payload.responsePhase==='next_morning'?'high':'medium'};
}

export function adaptNextQuality({items=[],events=[],config={},today=new Date().toISOString().slice(0,10)}={}){
  const signal=responseSignal({items,events,today});if(!signal||signal.mode==='RECOVERY')return null;const target=items.filter(row=>isQuality(row)&&row.localDate>=today&&row.localDate>signal.localDate&&row.lockLevel!=='user'&&row.lockLevel!=='system'&&!row.explicitChoice).sort((a,b)=>a.localDate.localeCompare(b.localDate))[0];if(!target||target.plannedLoad?.bakken?.evidenceId===signal.eventId)return null;const week=monday(target.localDate),weekRows=items.filter(row=>monday(row.localDate)===week),qualityRows=weekRows.filter(isQuality).sort((a,b)=>a.localDate.localeCompare(b.localDate)),slot=Math.max(0,qualityRows.findIndex(row=>row.workoutId===target.workoutId)),currentId=String(target.plannedLoad?.bakken?.sessionId||''),selection=selectQualitySession({date:target.localDate,slot,week,config,history:sessionHistory(items),expectedQuality:qualityRows.length,hasRace:weekRows.some(row=>row.workoutType==='race'),responseMode:signal.mode,excludeIds:signal.mode==='REDUCE'?[]:[currentId].filter(Boolean)}),after=applyBakkenSession(target,selection,{evidenceId:signal.eventId,reasonCodes:signal.reasonCodes}),changed=JSON.stringify([target.title,target.intent,target.prescription,target.plannedLoad?.bakken])!==JSON.stringify([after.title,after.intent,after.prescription,after.plannedLoad?.bakken]);if(!changed)return null;return{signal,target,before:target,after,rows:items.map(row=>row.workoutId===target.workoutId?after:row),summary:signal.mode==='REDUCE'?'Neste kvalitetsøkt er ført tilbake til en kontrollert terskeldose.':signal.mode==='HOLD'?'Neste kvalitetsøkt er valgt med lavere kostnad og samme fysiologiske retning.':'Neste kvalitetsøkt er dosert ut fra kontrollert respons og aktiv fase.',consequence:'Bare neste ulåste kvalitetsøkt endres. Historikk, løpsmål og resten av ukeplanen står.'};
}
