import { config as normalizeConfig,dateOnly,finite } from './validation.js';
import { constrainExisting } from './plan-engine.js';
import { event,newId } from './events.js';
import { activePlan,athleteConfig,activateDraft,createDraft } from './repository.js';
const parse=(value,fallback)=>{try{return JSON.parse(value)}catch{return fallback}};
const canonical=value=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().filter(key=>key!=='sourceHash'&&value[key]!==undefined).map(key=>[key,canonical(value[key])])):value;
async function sourceDigest(input){const bytes=new TextEncoder().encode(JSON.stringify(canonical(input))),digest=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('')}
function normalizedItem(row,index){
  const localDate=dateOnly(row.localDate||row.ds||row.date),workoutType=row.workoutType||row.type||'easy',sourceWorkoutId=String(row.workoutId||row.baseDs||''),workoutId=sourceWorkoutId?(sourceWorkoutId.startsWith('wo-')?sourceWorkoutId:`wo-${sourceWorkoutId.replace(/[^a-z0-9-]/gi,'-')}`):newId('wo'),legacy={baseDs:row.baseDs||row.ds||localDate,sourceLabel:row.sourceLabel||row.label||'',desc:row.desc||'',detail:row.detail||'',shoe:row.shoe||'',fuel:row.fuel||''},prescription={version:1,...(row.prescription||{}),legacy:{...legacy,...(row.prescription?.legacy||{})}};
  return{workoutId,lineageId:String(row.lineageId||workoutId),localDate,slotIndex:Number(row.slotIndex||0),status:row.status==='done'||row.terminal?'completed':row.status||'scheduled',sport:row.sport||(['cross','rest'].includes(workoutType)?workoutType:'running'),workoutType,title:String(row.title||'Planlagt økt'),intent:String(row.intent||row.stimulus||''),prescription,plannedDurationSeconds:finite(row.plannedDurationSeconds)||null,plannedDistanceM:finite(row.plannedDistanceM)||finite(row.km)*1000,plannedLoad:row.plannedLoad||{},source:'legacy-v10.25.1',lockLevel:row.locked?'user':'none',flexible:row.flexible===true,explicitChoice:row.explicitChoice===true||!!row.mode,index};
}
export function migrationPreview(input={},today=new Date().toISOString().slice(0,10)){
  const normalizedConfig=normalizeConfig({profile:input.profile||{},constraints:input.constraints||{},goal:input.goal||{}}),source=(input.effectivePlan||input.plan||[]).map(normalizedItem).filter(row=>row.localDate),result=constrainExisting(source,normalizedConfig,today);
  const beforeRuns=source.filter(row=>row.localDate>=today&&row.sport==='running').length,afterRuns=result.rows.filter(row=>row.localDate>=today&&row.sport==='running').length;
  return{config:normalizedConfig,items:result.rows,validation:result.validation,summary:{sourceItems:source.length,resultItems:result.rows.length,removedDefaultRuns:Math.max(0,beforeRuns-afterRuns)}};
}
export async function commitMigration(env,userId,input={},correlationId=''){
  const sourceHash=String(input.sourceHash||'').slice(0,128);if(!sourceHash)throw new Error('INVALID_SOURCE_HASH');
  if(sourceHash!==await sourceDigest(input))throw new Error('SOURCE_HASH_MISMATCH');
  const existing=await env.DB.prepare("SELECT status,source_hash,result_plan_revision_id FROM rb_migrations WHERE user_id=?1 AND migration_key='coach-loop-v1026'").bind(userId).first();
  if(existing?.status==='committed'){if(existing.source_hash!==sourceHash)throw new Error('SOURCE_HASH_CONFLICT');const plan=await activePlan(env.DB,userId);return{ok:true,idempotent:true,planRevisionId:existing.result_plan_revision_id,plan}}
  const preview=migrationPreview(input),now=new Date().toISOString(),cfg=preview.config,configExisting=await athleteConfig(env.DB,userId),sourceEvent=event({userId,type:'migration:coach-loop-v1026',source:'runnerbear',sourceId:sourceHash,localDate:now.slice(0,10),payload:{sourceHash,summary:preview.summary,previousConfigRevision:configExisting?.revision||0},now}),planRevisionId=await createDraft(env.DB,{userId,parentRevisionId:null,reasonCode:'migration-preview',items:preview.items,now}),compatibility=await compatibilityProjectionStatements(env.DB,userId,planRevisionId,preview.items,now),migrationStatement=env.DB.prepare(`INSERT INTO rb_migrations(user_id,migration_key,source_hash,status,result_plan_revision_id,detail_json,started_at,completed_at)
    VALUES(?1,'coach-loop-v1026',?2,'committed',?3,?4,?5,?5) ON CONFLICT(user_id,migration_key) DO UPDATE SET source_hash=excluded.source_hash,status='committed',result_plan_revision_id=excluded.result_plan_revision_id,detail_json=excluded.detail_json,completed_at=excluded.completed_at`).bind(userId,sourceHash,planRevisionId,JSON.stringify(preview.summary),now);
  await activateDraft(env.DB,{userId,planRevisionId,parentRevisionId:null,reasonCode:'migration',sourceEvent,config:cfg,timezone:input.timezone||'Europe/Oslo',now,extraStatements:[...compatibility,migrationStatement]});
  console.log(JSON.stringify({event:'coach_loop_migration',build:'11.1.0',policyVersion:'bakken-adaptive-coach-3',correlationId,userScope:userId==='primary'?'owner':'user',planRevisionId,status:'committed',reasonCode:'LEGACY_SNAPSHOT_MIGRATED'}));
  return{ok:true,idempotent:false,planRevisionId,plan:await activePlan(env.DB,userId),summary:preview.summary};
}
export async function compatibilityProjectionStatements(db,userId,planRevisionId,items,now=new Date().toISOString(),localPatch={}){
  const statements=[db.prepare('DELETE FROM rb_plan_days WHERE user_id=?1 AND date>=?2').bind(userId,now.slice(0,10))];
  for(const item of items.filter(row=>row.localDate>=now.slice(0,10)))statements.push(db.prepare(`INSERT INTO rb_plan_days(user_id,date,goal_id,type,title,km,status,payload_json,updated_at)
    VALUES(?1,?2,'',?3,?4,?5,?6,?7,?8) ON CONFLICT(user_id,date) DO UPDATE SET type=excluded.type,title=excluded.title,km=excluded.km,status=excluded.status,payload_json=excluded.payload_json,updated_at=excluded.updated_at`).bind(userId,item.localDate,item.workoutType,item.title,finite(item.plannedDistanceM)/1000,item.status,JSON.stringify({...item,planRevisionId}),now));
  const stateRow=await db.prepare("SELECT payload_json FROM rb_state WHERE user_id=?1 AND namespace='localStorage'").bind(userId).first(),local=parse(stateRow?.payload_json,{}),moves={},adjustments={},locks={};
  for(const item of items.filter(row=>row.localDate>=now.slice(0,10))){const legacy=item.prescription?.legacy||{},baseDs=dateOnly(legacy.baseDs)||String(item.workoutId||'').replace(/^wo-/,'').slice(0,10),sourceLabel=legacy.sourceLabel||'';if(baseDs&&baseDs!==item.localDate)moves[baseDs]=item.localDate;if(sourceLabel)adjustments[sourceLabel]={created:now,source:'runnerbear-v11.0-compatibility',reason:'canonical-projection',type:item.workoutType,title:item.title,desc:legacy.desc||'',detail:legacy.detail||'',km:finite(item.plannedDistanceM)/1000,shoe:legacy.shoe||'',fuel:legacy.fuel||''};if(baseDs&&item.lockLevel==='user')locks[baseDs]=true}
  local.runnerbear_v107_plan_moves=JSON.stringify(moves);local.runfest26_week_adjustments=JSON.stringify(adjustments);local.runnerbear_v107_plan_locks=JSON.stringify(locks);local.runnerbear_v10251_plan_revision=String(Math.max(1,Number(local.runnerbear_v10251_plan_revision||0)+1));local.runnerbear_v1027_compatibility_revision=JSON.stringify({planRevisionId,projectedAt:now});Object.assign(local,localPatch||{});
  statements.push(db.prepare(`INSERT INTO rb_state(user_id,namespace,payload_json,updated_at) VALUES(?1,'localStorage',?2,?3) ON CONFLICT(user_id,namespace) DO UPDATE SET payload_json=excluded.payload_json,updated_at=excluded.updated_at`).bind(userId,JSON.stringify(local),now));
  return statements;
}
export async function compatibilityProjection(db,userId,planRevisionId,items,now=new Date().toISOString()){await db.batch(await compatibilityProjectionStatements(db,userId,planRevisionId,items,now))}
