import { BUILD,SCHEMA_VERSION } from './constants.js';
import { activePlan,athleteConfig,flags,latestDecision,syncStatus } from './repository.js';
import { assessGoalConfidence,buildCoachBrief } from './coach-engine.js';
import { buildRealignmentProposal,buildWeeklyReview } from './review-engine.js';
import { buildSyncRepair } from './sync-repair.js';
import { bodyResponseFor,publicBodyResponse } from './body-response.js';
const parse=(value,fallback)=>{try{return JSON.parse(value)}catch{return fallback}};
const addDays=(date,days)=>new Date(Date.parse(`${date}T12:00:00Z`)+days*86400000).toISOString().slice(0,10);
async function responseState(db,userId,scope='home'){
  const activityLimit=scope==='full'?400:90,eventLimit=scope==='full'?400:120;
  const [health,sync,activities,events]=await Promise.all([
    db.prepare('SELECT date,hrv_ms,sleep_seconds,rhr_bpm,payload_json,updated_at FROM rb_health_daily WHERE user_id=?1 ORDER BY date DESC LIMIT 21').bind(userId).all(),
    db.prepare("SELECT last_synced_at,status,updated_at FROM rb_sync_sources WHERE user_id=?1 AND source IN ('tredict','garmin') ORDER BY updated_at DESC LIMIT 1").bind(userId).first(),
    db.prepare(`SELECT source,source_id,date,sport_type,sub_sport_type,title,duration_seconds,distance_m,avg_hr,payload_json,updated_at FROM rb_activities WHERE user_id=?1 ORDER BY date DESC,updated_at DESC LIMIT ${activityLimit}`).bind(userId).all(),
    db.prepare(`SELECT event_id,event_type,occurred_at,local_date,quality,payload_json FROM rb_training_events WHERE user_id=?1 ORDER BY occurred_at DESC LIMIT ${eventLimit}`).bind(userId).all(),
  ]);
  const healthRows=(health.results||[]).map(row=>({...row,payload:parse(row.payload_json,{})})),activityRows=(activities.results||[]).map(row=>({...row,payload:parse(row.payload_json,{})})),eventRows=(events.results||[]).map(row=>({...row,payload:parse(row.payload_json,{})}));
  const latest=healthRows[0]||null,measurement=latest?`${latest.date}T06:00:00.000Z`:null,ingested=sync?.last_synced_at||latest?.updated_at||null;
  const ageHours=value=>value?Math.max(0,(Date.now()-Date.parse(value))/3600000):null,measurementAge=ageHours(measurement),syncAge=ageHours(ingested),freshness=measurementAge==null||measurementAge>36||syncAge==null?'stale':measurementAge<=18&&syncAge<=6?'fresh':'partial';
  return{health:{latest,days:healthRows.length,measurementTime:measurement,ingestionTime:ingested,freshness,baselineEstablished:healthRows.slice(1).filter(row=>Number.isFinite(Number(row.hrv_ms))||Number.isFinite(Number(row.sleep_seconds))||Number.isFinite(Number(row.rhr_bpm))).length>=10},recentActivities:activityRows,responseEvents:eventRows,syncSource:sync||null};
}
function goalConfidence(plan,response){const activityDates=new Set(response.recentActivities.map(row=>row.date)),responses=new Set(response.responseEvents.filter(row=>row.event_type==='feedback:workout'&&row.payload?.responsePhase==='next_morning').map(row=>String(row.payload?.workoutId||''))),points=(plan.items||[]).filter(row=>(row.workoutType==='quality'||/gate/i.test(row.title||''))&&(row.status==='completed'||activityDates.has(row.localDate))).map(row=>({workoutId:row.workoutId,date:row.localDate,kind:/gate/i.test(row.title||'')?'gate':'quality',nextDayResponse:responses.has(String(row.workoutId))})),vo2Available=response.recentActivities.some(row=>{const payload=row.payload||{};return Number.isFinite(Number(payload.vo2Max??payload.vo2_max??payload.vo2max))});return assessGoalConfidence({points,vo2Available})}
function publicRealignment(proposal){if(!proposal)return null;const {rows,changes,...summary}=proposal;return{...summary,changes:(changes||[]).map(change=>({workoutId:change.workoutId,localDate:change.localDate}))}}
export async function bootstrapV2(env,userId,scope='home'){
  const [featureFlags,config,plan]=await Promise.all([flags(env.DB,userId),athleteConfig(env.DB,userId),activePlan(env.DB,userId)]);
  if(!config||!plan)return{ok:true,build:BUILD,schemaVersion:SCHEMA_VERSION,needsMigration:true,flags:featureFlags,generatedAt:new Date().toISOString()};
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:config.timezone||'Europe/Oslo'}).format(new Date()),todayWorkout=plan.items.find(item=>item.localDate===today)||null;
  const generatedAt=new Date().toISOString(),[coachDecision,sync,response,bodyResponse]=await Promise.all([latestDecision(env.DB,userId,plan.planRevisionId),syncStatus(env.DB,userId),responseState(env.DB,userId,scope),bodyResponseFor(env.DB,userId,{plan,today,now:generatedAt})]);
  const visiblePlan=scope==='home'?{...plan,items:plan.items.filter(item=>item.localDate>=addDays(today,-35)&&item.localDate<=addDays(today,14))}:plan;
  const coachBrief=buildCoachBrief({plan,decision:coachDecision,today,now:generatedAt}),weeklyReview=buildWeeklyReview({plan,activities:response.recentActivities,events:response.responseEvents,today,generatedAt}),realignmentProposal=buildRealignmentProposal({plan,activities:response.recentActivities,events:response.responseEvents,config,today,generatedAt}),syncRepair=buildSyncRepair(sync,plan.planRevisionId),visibleBodyResponse=publicBodyResponse(bodyResponse);
  return{ok:true,build:BUILD,schemaVersion:SCHEMA_VERSION,needsMigration:false,planRevisionId:plan.planRevisionId,cursor:`${plan.planRevisionId}:${coachDecision?.inputCursor||'none'}`,generatedAt,generatedFromDate:plan.generatedFromDate,trigger:plan.trigger,flags:featureFlags,config,activePlan:visiblePlan,todayWorkout,coachDecision,coachBrief,weeklyReview,realignmentProposal:publicRealignment(realignmentProposal),syncRepair,bodyResponse:visibleBodyResponse,healthSummary:{state:visibleBodyResponse.state,summary:visibleBodyResponse.summary,metrics:visibleBodyResponse.metrics},baselineStatus:visibleBodyResponse.baselineStatus,healthDataFreshness:visibleBodyResponse.freshness,readiness:{freshness:visibleBodyResponse.freshness.status,baselineEstablished:visibleBodyResponse.baselineStatus.status==='established',latest:response.health.latest},recentActivities:response.recentActivities,responseEvents:response.responseEvents,goalConfidence:featureFlags.coach_loop_goal_confidence?goalConfidence(plan,response):null,syncSource:response.syncSource,sync};
}
export async function compatibilityBootstrap(env,userId,scope='home'){
  const rows=await env.DB.prepare('SELECT date,type,title,km,status,payload_json,updated_at FROM rb_plan_days WHERE user_id=?1 ORDER BY date').bind(userId).all(),items=(rows.results||[]).map((row,index)=>{const payload=parse(row.payload_json,{});return{...payload,workoutId:payload.workoutId||`legacy-${row.date}-${index}`,lineageId:payload.lineageId||payload.workoutId||`legacy-${row.date}-${index}`,planRevisionId:'compatibility-v1',localDate:row.date,slotIndex:index,status:row.status||'scheduled',sport:payload.sport||(['easy','quality','race'].includes(row.type)?'running':row.type||'rest'),workoutType:row.type||payload.workoutType||'easy',title:row.title||payload.title||'Planlagt økt',plannedDistanceM:Number(row.km||0)*1000,lockLevel:payload.lockLevel||'none'}}),today=new Date().toISOString().slice(0,10),featureFlags=await flags(env.DB,userId);
  return{ok:true,build:BUILD,schemaVersion:SCHEMA_VERSION,compatibilityFallback:true,needsMigration:false,planRevisionId:'compatibility-v1',cursor:`compatibility-v1:${rows.results?.[0]?.updated_at||'empty'}`,generatedAt:new Date().toISOString(),flags:{...featureFlags,coach_loop_read:false,coach_loop_ui:false,coach_loop_write:false,coach_loop_sync:false,coach_loop_safe_auto:false},config:null,activePlan:{planRevisionId:'compatibility-v1',status:'active',items:scope==='home'?items.filter(item=>item.localDate>=addDays(today,-35)&&item.localDate<=addDays(today,14)):items},todayWorkout:items.find(item=>item.localDate===today)||null,coachDecision:null,coachBrief:null,bodyResponse:{version:'body-response-1',planRevisionId:'compatibility-v1',state:'wait_for_data',stateLabel:'Venter på ferske data',confidence:'low',summary:'RunnerBear viser ikke et eldre helsegrunnlag som gjeldende.',metrics:{},domains:[],reasonCodes:['STALE_HEALTH'],checkIn:{required:false,options:[]},freshness:{status:'stale'},baselineStatus:{status:'building',sampleCount:0}},readiness:{freshness:'stale',baselineEstablished:false},recentActivities:[],responseEvents:[],sync:[]};
}
